package studio.anva.characterpaper.tests;
import android.app.*;import android.os.*;import android.content.*;import android.webkit.*;import java.util.concurrent.*;import java.io.*;import android.net.Uri;
public class ReleaseChecks extends Instrumentation {
 private Activity activity;private WebView web;
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 private String js(String script)throws Exception{CountDownLatch latch=new CountDownLatch(1);String[] value={null};runOnMainSync(()->web.evaluateJavascript(script,v->{value[0]=v;latch.countDown();}));if(!latch.await(30,TimeUnit.SECONDS))throw new Exception("WebView check timed out");return value[0];}
 private void require(boolean condition,String message)throws Exception{if(!condition)throw new Exception(message);}
 @Override public void onStart(){Bundle report=new Bundle();try{
  Intent i=new Intent();i.setClassName("studio.anva.characterpaper","studio.anva.characterpaper.MainActivity");i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);activity=startActivitySync(i);runOnMainSync(()->{android.view.ViewGroup root=activity.findViewById(android.R.id.content);android.view.ViewGroup frame=(android.view.ViewGroup)root.getChildAt(0);web=(WebView)frame.getChildAt(0);});
  for(int n=0;n<80;n++){if("true".equals(js("!!document.querySelector('.welcome-hero')")))break;Thread.sleep(500);}
  require("true".equals(js("!!document.querySelector('.welcome-hero')")),"Welcome did not open: "+js("JSON.stringify({url:location.href,state:document.readyState,html:document.documentElement.outerHTML})"));
  require("true".equals(js("typeof PaperNative!=='undefined'&&PaperRelease.platform==='Android'&&Paper.contexts.includes('game')")),"Android bridge/context missing");
  js("window.checkDone=false;window.checkFailure='';(async()=>{try{const boot=await(await fetch('/api/bootstrap')).json();const p=boot.profiles.find(p=>p.example);const r=await api09('unlock',{id:p.id});token=r.token;profile09=r.profile;w=Paper.migrate(r.state);saved=Paper.clone(w);revision=r.revision;native=true;dirty=true;w.characters[0].notes='Android persistence check';if(!await save())throw Error(lastError);await lock09();await new Promise(r=>setTimeout(r,1600));const r2=await api09('unlock',{id:p.id});if(r2.state.characters[0].notes!=='Android persistence check')throw Error('Save was not persisted');token=r2.token;const reset=await api09('example-reset');if(!reset.state.characters[0].notes.includes('original sample'))throw Error('Reset failed');const out=Paper.exportCharacter(reset.state.characters[0],reset.state,{context:'game'}).text;if(!out.includes('Narrative use:')||out.includes('Private creator note'))throw Error('Game/privacy failed');w=Paper.migrate(reset.state);saved=Paper.clone(w);revision=reset.revision;profile09=r2.profile;ui.id=null;ui.page='home';render();window.checkVersion=PaperRelease.version;}catch(e){window.checkFailure=e.message}finally{window.checkDone=true}})()");
  for(int n=0;n<120;n++){if("true".equals(js("window.checkDone")))break;Thread.sleep(500);}
  require("true".equals(js("window.checkDone")),"Persistence check timed out");require("\"\"".equals(js("window.checkFailure")),"Check failed: "+js("window.checkFailure"));
  js("notice('Back navigation check')");runOnMainSync(()->activity.onBackPressed());for(int n=0;n<30&&"true".equals(js("modal.open"));n++)Thread.sleep(100);require("false".equals(js("modal.open")),"Android Back did not close the dialog");
  js("w.characters[0].notes+='\\nLifecycle autosave check';dirty=true");runOnMainSync(()->callActivityOnPause(activity));for(int n=0;n<50&&"true".equals(js("dirty||!!saving"));n++)Thread.sleep(100);runOnMainSync(()->callActivityOnResume(activity));require("false".equals(js("dirty||!!saving")),"Background autosave did not complete");
  File exported=new File(activity.getFilesDir(),"instrumented-export.txt");exported.delete();
  ActivityMonitor monitor=new ActivityMonitor(){@Override public ActivityResult onStartActivity(Intent intent){if(Intent.ACTION_CREATE_DOCUMENT.equals(intent.getAction()))return new ActivityResult(Activity.RESULT_OK,new Intent().setData(Uri.fromFile(exported)));return null;}};addMonitor(monitor);
  js("PaperNative.save('test.txt','text/plain',btoa('Character Paper native export check'))");
  for(int n=0;n<60&&!exported.exists();n++)Thread.sleep(100);
  require(exported.exists()&&new String(java.nio.file.Files.readAllBytes(exported.toPath()),"UTF-8").equals("Character Paper native export check"),"Native document export failed");removeMonitor(monitor);exported.delete();
  ActivityMonitor picker=new ActivityMonitor(){@Override public ActivityResult onStartActivity(Intent intent){if(Intent.ACTION_OPEN_DOCUMENT.equals(intent.getAction()))return new ActivityResult(Activity.RESULT_OK,new Intent().setData(Uri.parse("content://studio.anva.characterpaper.tests.files/sample")));return null;}};addMonitor(picker);
  js("(()=>{window.fixtureRead='';const input=document.createElement('input');input.type='file';input.onchange=()=>{const reader=new FileReader();reader.onload=()=>window.fixtureRead=reader.result;reader.readAsText(input.files[0])};input.style='position:fixed;left:10px;top:10px;width:180px;height:60px;z-index:99999';document.body.append(input)})()");
  int[] pos=new int[2];runOnMainSync(()->web.getLocationOnScreen(pos));float density=activity.getResources().getDisplayMetrics().density;long tapTime=SystemClock.uptimeMillis();sendPointerSync(android.view.MotionEvent.obtain(tapTime,tapTime,android.view.MotionEvent.ACTION_DOWN,pos[0]+40*density,pos[1]+35*density,0));sendPointerSync(android.view.MotionEvent.obtain(tapTime,tapTime+50,android.view.MotionEvent.ACTION_UP,pos[0]+40*density,pos[1]+35*density,0));
  for(int n=0;n<60;n++){if(js("window.fixtureRead").contains("Character Paper"))break;Thread.sleep(100);}
  require(js("window.fixtureRead").contains("Character Paper"),"Native file picker did not return readable content");removeMonitor(picker);
  String originalUrl=js("location.href");runOnMainSync(()->activity.setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE));Thread.sleep(700);require(originalUrl.equals(js("location.href")),"Rotation changed local page");runOnMainSync(()->activity.setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_PORTRAIT));
  report.putString("result","PASS: Android startup, owned-asset bridge, sample media, app-local save/reopen, reset, Game export, Notes privacy, native document save/import, rotation, Back navigation and background autosave");report.putString("version",js("window.checkVersion"));finish(Activity.RESULT_OK,report);
 }catch(Exception e){report.putString("result","FAIL: "+e);finish(Activity.RESULT_CANCELED,report);}}
}
