package studio.anva.characterpaper;

import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.webkit.*;import android.view.*;import android.widget.*;import android.util.Base64;
import org.json.*;import java.io.*;import java.nio.file.*;import java.util.*;

public class MainActivity extends Activity {
 private WebView web;private File profiles;private ValueCallback<Uri[]> chooser;private String saveMime,saveName;private final int PICK=10,SAVE=11;
 private static final String ORIGIN="https://paper.local/";
 private static final Set<String> LINKS=new HashSet<>(Arrays.asList("https://anva-studio.github.io/","https://forms.gle/W7qtQRmqxgZkLtS9","mailto:Anvahq@gmail.com","https://buymeacoffee.com/anva"));
 @Override public void onCreate(Bundle state){super.onCreate(state);profiles=new File(getFilesDir(),"profiles");profiles.mkdirs();LinearLayout frame=new LinearLayout(this);frame.setBackgroundColor(0xfff7f3eb);web=new WebView(this);frame.addView(web,new LinearLayout.LayoutParams(-1,-1));setContentView(frame);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
 if(Build.VERSION.SDK_INT>=30)frame.setOnApplyWindowInsetsListener((v,in)->{android.graphics.Insets i=in.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());v.setPadding(i.left,i.top,i.right,i.bottom);return in;});else frame.setFitsSystemWindows(true);
 WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(true);s.setAllowFileAccessFromFileURLs(false);s.setAllowUniversalAccessFromFileURLs(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setSupportMultipleWindows(false);s.setMediaPlaybackRequiresUserGesture(true);s.setSaveFormData(false);web.addJavascriptInterface(new Bridge(),"PaperNative");
 web.setWebViewClient(new WebViewClient(){@Override public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame())android.util.Log.e("CharacterPaper", "Local page load failed: "+e.getErrorCode()+" "+e.getDescription());}@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){if(r.getUrl().toString().equals(ORIGIN+"index.html"))return false;externalUrl(r.getUrl().toString());return true;}@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest req){Uri uri=req.getUrl();try{if(!"https".equals(uri.getScheme())||!"paper.local".equals(uri.getHost()))return blocked();String name=uri.getPath().substring(1);if(!name.matches("[A-Za-z0-9_.-]+")||!req.getMethod().equals("GET"))return blocked();String mime=name.endsWith(".js")?"text/javascript":name.endsWith(".css")?"text/css":name.endsWith(".png")?"image/png":name.endsWith(".svg")?"image/svg+xml":"text/html";Map<String,String> h=new HashMap<>();h.put("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-src 'none'");h.put("X-Content-Type-Options","nosniff");return new WebResourceResponse(mime,"UTF-8",200,"OK",h,getAssets().open("www/"+name));}catch(Exception e){android.util.Log.e("CharacterPaper","Asset failed "+uri,e);return blocked();}}});
 web.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> callback,FileChooserParams params){if(chooser!=null)chooser.onReceiveValue(null);chooser=callback;Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT);pick.addCategory(Intent.CATEGORY_OPENABLE);String[] types=params.getAcceptTypes();String type=types.length==1&&!types[0].contains(",")&&!types[0].startsWith(".")?types[0]:"*/*";pick.setType(type);pick.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,params.getMode()==FileChooserParams.MODE_OPEN_MULTIPLE);try{startActivityForResult(pick,PICK);}catch(ActivityNotFoundException e){chooser.onReceiveValue(null);chooser=null;Toast.makeText(MainActivity.this,"No file picker is available.",Toast.LENGTH_LONG).show();}return true;}});
 if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,()->onBackPressed());
 if(state==null)new File(getCacheDir(),"pending-export").delete();
 if(state!=null){saveMime=state.getString("saveMime");saveName=state.getString("saveName");}web.loadUrl(ORIGIN+"index.html");
 }
 private WebResourceResponse blocked(){return new WebResourceResponse("text/plain","UTF-8",403,"Blocked",new HashMap<>(),new ByteArrayInputStream(new byte[0]));}
 private void externalUrl(String url){if(!LINKS.contains(url))return;runOnUiThread(()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(ActivityNotFoundException e){Toast.makeText(this,"No app is available to open this link.",Toast.LENGTH_LONG).show();}});}
 private File record(String id)throws IOException{if(id==null||!id.matches("[A-Za-z0-9-]{1,100}"))throw new IOException("Invalid profile.");return new File(profiles,id+".json");}
 private String error(Exception e){JSONObject j=new JSONObject();try{j.put("error",e.getMessage());}catch(Exception ignored){}return j.toString();}
 private void atomic(File file,byte[] data)throws IOException{File temp=new File(file.getPath()+".pending");try(FileOutputStream out=new FileOutputStream(temp)){out.write(data);out.getFD().sync();}try{Files.move(temp.toPath(),file.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException e){Files.move(temp.toPath(),file.toPath(),StandardCopyOption.REPLACE_EXISTING);}}
 public class Bridge {
  @JavascriptInterface public synchronized String list(){JSONArray a=new JSONArray();File[] files=profiles.listFiles();if(files!=null)for(File f:files)if(f.getName().endsWith(".json"))a.put(f.getName().substring(0,f.getName().length()-5));return a.toString();}
  @JavascriptInterface public synchronized String read(String id){try{File f=record(id);return f.exists()?new String(Files.readAllBytes(f.toPath()),java.nio.charset.StandardCharsets.UTF_8):"null";}catch(Exception e){return error(e);}}
  @JavascriptInterface public synchronized String write(String json){try{if(json.length()>210*1024*1024)throw new IOException("Profile exceeds storage limit.");JSONObject r=new JSONObject(json);atomic(record(r.getString("id")),json.getBytes(java.nio.charset.StandardCharsets.UTF_8));return "{\"ok\":true}";}catch(Exception e){return error(e);}}
  @JavascriptInterface public synchronized String remove(String id){try{Files.delete(record(id).toPath());return "{\"ok\":true}";}catch(Exception e){return error(e);}}
  @JavascriptInterface public synchronized boolean initialized(){return new File(profiles,".example-initialized").exists();}
  @JavascriptInterface public synchronized void initialize(){try{atomic(new File(profiles,".example-initialized"),new byte[]{1});}catch(Exception e){throw new IllegalStateException(e);}}
  @JavascriptInterface public void external(String url){externalUrl(url);}
  @JavascriptInterface public void finish(){runOnUiThread(()->MainActivity.this.finish());}
  @JavascriptInterface public void save(String name,String mime,String data){try{if(data.length()>280*1024*1024)throw new IOException("Export exceeds file limit.");synchronized(MainActivity.this){File pending=new File(getCacheDir(),"pending-export");if(pending.exists())throw new IOException("Finish the current Save file dialog first.");atomic(pending,Base64.decode(data,Base64.DEFAULT));saveName=name.replaceAll("[\\\\/:*?\"<>|]","_");saveMime=mime;}runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(saveMime);i.putExtra(Intent.EXTRA_TITLE,saveName);try{startActivityForResult(i,SAVE);}catch(Exception e){new File(getCacheDir(),"pending-export").delete();fileSaved(false,e.getMessage());}});}catch(Exception e){runOnUiThread(()->fileSaved(false,e.getMessage()));}}
 }
 private void fileSaved(boolean ok,String message){web.evaluateJavascript("window.paperFileSaved&&paperFileSaved("+ok+","+JSONObject.quote(message==null?"":message)+")",null);}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==PICK){if(chooser!=null){ArrayList<Uri> uris=new ArrayList<>();if(result==RESULT_OK&&data!=null){if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)uris.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)uris.add(data.getData());}chooser.onReceiveValue(uris.isEmpty()?null:uris.toArray(new Uri[0]));chooser=null;}}if(request==SAVE){File pending=new File(getCacheDir(),"pending-export");if(result==RESULT_OK&&data!=null&&data.getData()!=null){new Thread(()->{try(InputStream in=new FileInputStream(pending);OutputStream out=getContentResolver().openOutputStream(data.getData(),"wt")){if(out==null)throw new IOException("Could not open destination.");byte[] buf=new byte[32768];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);runOnUiThread(()->fileSaved(true,""));}catch(Exception e){runOnUiThread(()->fileSaved(false,e.getMessage()));}finally{pending.delete();}}).start();}else pending.delete();}}
 @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);out.putString("saveMime",saveMime);out.putString("saveName",saveName);}
 @Override public void onBackPressed(){web.evaluateJavascript("window.paperBack&&paperBack()",null);}
 @Override protected void onPause(){web.evaluateJavascript("window.paperPause&&paperPause()",null);super.onPause();}
 @Override protected void onDestroy(){if(chooser!=null)chooser.onReceiveValue(null);web.removeJavascriptInterface("PaperNative");web.destroy();super.onDestroy();}
}
