'use strict';
const P=Paper,$=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let w=P.empty(),saved=null,revision=0,token='',native=false,db=null,dirty=false,generation=0,timer=null,saving=null,lastError='',undo=[],redo=[],editStamp=0;
let ui={page:'characters',id:null,tab:'Loose pages',query:'',filter:'all',archive:false,focus:false,chapter:null,showEmpty:false,projectTab:'Contents'};
const modal=$('#modal');let afterModal=null;
const btn=(text,action,value='',cls='')=>`<button class="${cls}" data-action="${action}" data-value="${esc(value)}">${text}</button>`;
const input=(label,path,value,kind='input',extra='')=>`<label>${esc(label)}${kind==='textarea'?`<textarea data-bind="${path}" ${extra}>${esc(value)}</textarea>`:`<input data-bind="${path}" value="${esc(value)}" ${extra}>`}</label>`;
const select=(label,path,value,choices)=>`<label>${esc(label)}<select data-bind="${path}">${choices.map(([v,t])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
const check=(label,path,value)=>`<label class="check"><input type="checkbox" data-bind="${path}" ${value?'checked':''}>${esc(label)}</label>`;
const colors=['#405b59','#65516e','#3f5475','#8a5a49','#465ccc'];
function object(){return [...w.characters,...w.stories,...w.projects].find(x=>x.id===ui.id)}
function objectPath(){for(const k of ['characters','stories','projects']){const i=w[k].findIndex(x=>x.id===ui.id);if(i>=0)return k+'.'+i}return ''}
function at(path){return path.split('.').reduce((o,k)=>o?.[k],w)}
function set(path,value){const ks=path.split('.'),key=ks.pop();let o=w;for(const k of ks)o=o[k];o[key]=value}
function transact(fn,renderNow=true){checkpoint();fn();changed();if(renderNow)render()}
function checkpoint(group=false){if(group&&Date.now()-editStamp<900)return;const size=JSON.stringify(w).length;undo.push(P.clone(w));const limit=Math.max(1,Math.min(25,Math.floor(24000000/Math.max(size,1))));while(undo.length>limit)undo.shift();redo=[];editStamp=Date.now()}
function changed(){dirty=true;generation++;if(object())object().updated=Date.now();clearTimeout(timer);if(w.settings.autosave)timer=setTimeout(()=>save(),800);status()}
function status(){const node=$('#save-status');node.className=lastError?'failed':'';node.innerHTML=lastError?`<span>Save failed: ${esc(lastError)}</span> ${btn('Retry','save')} ${btn('Download unsaved backup','backup')}`:saving?'◌ Saving…':dirty?(w.settings.autosave?'◌ Autosave on · changes pending':`Unsaved changes ${btn('Save','save')}`):`✓ ${w.settings.autosave?'Autosave on · ':''}Saved ${native?'locally':'in this browser'}`}
async function idbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open('character-paper-v08',1);r.onupgradeneeded=()=>r.result.createObjectStore('library');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function idbGet(){return new Promise((resolve,reject)=>{const r=db.transaction('library').objectStore('library').get('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function writeBrowser(state){return new Promise((resolve,reject)=>{const t=db.transaction('library','readwrite');t.objectStore('library').put(state,'state');t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error)})}
async function save(){clearTimeout(timer);if(saving){await saving;if(dirty&&!lastError)return save();return !lastError}if(!dirty)return true;
 const g=generation,state=P.clone(w);lastError='';
 saving=(async()=>{try{P.validate(state);if(native){const r=await fetch('/api/library',{method:'PUT',headers:{'Content-Type':'application/json','X-Paper-Token':token,'X-Paper-CSRF':csrf09},body:JSON.stringify({state,revision})});const v=await r.json();if(!r.ok)throw Error(v.error);revision=v.revision;if(profile09)profile09.savedAt=v.savedAt}else await writeBrowser(state);saved=state;if(g===generation)dirty=false;return true}catch(e){lastError=e.message;return false}})();status();const ok=await saving;saving=null;status();if(ok&&dirty)return save();return ok;
}
function dialog(title,html,buttons=[]){modal.innerHTML=`<div class="about-heading"><h2>${esc(title)}</h2>${btn('Close','close-modal')}</div>${html}<div class="dialog-actions">${buttons.map(b=>btn(b[0],b[1],b[2]||'',b[3]||'')).join('')}</div>`;bind(modal);if(!modal.open)modal.showModal()}
function notice(text){dialog('Character Paper',`<p>${esc(text)}</p>`)}
function closeDialog(){modal.close();afterModal=null}
async function navigate(fn){if(dirty){if(w.settings.autosave){if(!await save())return}else{afterModal=fn;dialog('Save your changes?', '<p>Save this library before leaving, discard unsaved changes, or keep editing.</p>',[['Keep editing','close-modal'],['Discard changes','discard'],['Save & continue','save-leave','','primary']]);return}}fn();render()}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
const safeName=name=>name.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,90)||'Character-Paper';
function fullBackup(){download('Character-Paper-backup.json',JSON.stringify(w,null,2))}
function openItem(id){navigate(()=>{ui.id=id;ui.tab=[...w.stories].some(o=>o.id===id)?'Writing':'Loose pages';ui.chapter=null;ui.focus=false})}
function move(arr,index,delta){if(index+delta<0||index+delta>=arr.length)return;[arr[index],arr[index+delta]]=[arr[index+delta],arr[index]]}
const reorder=(type,id)=>`${btn('↑',type,id+':-1','tiny')}${btn('↓',type,id+':1','tiny')}`;
function header(){return `<header class="topbar"><button class="brand flat" data-action="home"><img src="logo.svg" alt="" width="38" height="38"><span>Character Paper<small>A place for every character.</small></span></button><div class="top-actions">${btn('Undo','undo','','tiny')}${btn('Redo','redo','','tiny')}${btn('Backup','backup')}${btn('Restore backup','import')}${btn('Settings','settings')}${btn('About','about')}${btn(w.settings.dark?'☀ Light':'☾ Dark','theme')}</div></header>`}
function cover(o){const image=o.gallery.find(a=>a.id===o.cover?.id);return `<div class="cover" style="background:${o.color}">${image?`<div class="cover-image"><img alt="" src="${image.data}" style="object-position:${o.cover.x}% ${o.cover.y}%;transform:scale(${o.cover.zoom})"></div>`:''}<span class="book-label">${o.kind==='story'?'STORY':o.kind==='project'?'PROJECT':'CHARACTER PAPER'}</span><span class="monogram">${image?'':esc(o.name[0])}</span><span class="cover-title">${esc(o.name)}</span><span class="cover-sub">${o.kind==='character'?o.uses.join(' · ').toUpperCase():'A PLACE FOR YOUR WORDS'}</span></div>`}
function library(){let items=w[ui.page]||[];const q=ui.query.toLowerCase();items=items.filter(o=>!!o.archived===ui.archive).filter(o=>o.kind==='character'?(ui.filter==='all'||o.uses.includes(ui.filter))&&P.searchable(o).includes(q):[o.name,o.description||'',o.notes,...(o.chapters||[]).map(c=>c.text)].join(' ').toLowerCase().includes(q));return `<main class="library"><div class="heading"><div><span class="eyebrow">YOUR WRITING SPACE · v1.0.2</span><h1>${ui.page==='stories'?'A story starts here.':ui.page==='projects'?'Room for a whole world.':'Every character has a story.'}</h1><p>Keep their details. Explore their world. Leave room for what comes next.</p></div>${btn('+ New '+(ui.page==='characters'?'character':ui.page==='projects'?'Project':'Story'),'create',ui.page,'primary')}</div><div class="library-tabs">${['characters','stories','projects'].map(k=>btn(k[0].toUpperCase()+k.slice(1),'library',k,ui.page===k?'selected':'')).join('')}</div><div class="toolbar"><input id="library-search" aria-label="Search library" placeholder="Search your ${ui.page}…" value="${esc(ui.query)}">${ui.page==='characters'?`<div class="character-filter">${['all',...P.contexts].map(k=>btn(k[0].toUpperCase()+k.slice(1),'filter',k,ui.filter===k?'selected':'')).join('')}</div>`:''}${btn(ui.archive?'Show active':'Archive','toggle-archive')}<span class="count">${items.length} ${ui.page}</span></div><div class="books">${items.map(o=>`<div class="book-wrap"><button class="book-button" data-action="open" data-value="${o.id}" aria-label="Open ${esc(o.name)}">${cover(o)}<div class="book-meta"><strong>${esc(o.name)}</strong><small>${o.kind==='character'?o.uses.join(' · '):o.kind==='project'?o.members.length+' characters · '+o.stories.length+' stories':o.chapters.length+' writing parts'}</small></div></button>${ui.archive?btn('Unarchive','unarchive',o.id,'tiny'):''}</div>`).join('')}${!items.length?'<p class="empty">Nothing here yet. Start with a name, or change your search.</p>':''}</div></main>`}
function navItems(o){if(o.kind==='character')return [['Loose pages','Loose pages'],['Setup','Chatbot Setup'],...o.sections.map(s=>[s.id,s.name]),['Connections','Connections'],['Greetings','Greetings'],['Dialogue','Dialogue examples'],['Gallery','Gallery'],['References','References']].filter(([id])=>id!=='Setup'||o.view.includes('chatbot')).filter(([id])=>!['Greetings','Dialogue'].includes(id)||o.view.some(c=>['chatbot','roleplay'].includes(c))).filter(([id])=>{const s=o.sections.find(s=>s.id===id);return !s||P.applicable(s.scope,o.view)});if(o.kind==='story')return['Writing','Characters','References','Gallery','Notes'].map(x=>[x,x]);return['Contents','Connections','Gallery','Notes'].map(x=>[x,x])}
function shell(o){const path=objectPath();let nav=navItems(o);if(!nav.some(([id])=>id===ui.tab))ui.tab=nav[0][0];const full=nav;const pin=o.sections?.filter(s=>s.pinned&&nav.some(n=>n[0]===s.id))||[];if(o.kind==='character'&&w.settings.collapseEmpty&&!ui.showEmpty)nav=nav.filter(([id])=>{const s=o.sections.find(s=>s.id===id);return !s||P.hasContent(s)||s.id===ui.tab||s.pinned});const tabName=full.find(n=>n[0]===ui.tab)?.[1]||ui.tab;return `<div class="workspace ${ui.focus?'focus':''}"><aside>${btn('← Library','home','','flat back')}<div class="character-mini"><span class="avatar" style="background:${o.color}">${esc(o.name[0])}</span><div><strong>${esc(o.name)}</strong><small>${o.kind}</small></div></div>${pin.length?`<div class="nav-label">PINNED</div><nav>${pin.map(s=>btn('★ '+esc(s.name),'tab',s.id)).join('')}</nav>`:''}<nav>${nav.map(([id,title])=>btn(esc(title),'tab',id,id===ui.tab?'active':'')).join('')}</nav>${o.kind==='character'?`${btn('+ Custom section','new-section','','flat')}${btn(ui.showEmpty?'Minimize unused':'Show unused sections','show-empty','','flat')}`:''}</aside><main class="editor"><div class="editor-breadcrumb">${o.kind==='project'?'Project':o.kind==='story'?'Story':'Character Paper'} / ${esc(o.name)}</div><div class="editor-header"><div><span class="eyebrow">${esc(o.name)}</span><h1>${esc(tabName)}</h1></div><div class="story-actions">${btn(ui.focus?'Exit focus':'Focus','focus')}${btn('Book options','book-options')}${o.kind!=='project'?btn('Export','export','','primary'):''}</div></div>${o.kind==='character'?contextBar(o):''}${o.archived?'<p class="banner">This book is archived. You can still edit it.</p>':''}${content(o,path)}<footer class="page-footer"><span>Keep only the details that matter.</span><span id="word-count">${wordCount(o)} words</span></footer></main></div>`}
function wordCount(o){const text=o.kind==='story'?o.chapters.map(c=>c.text).join(' '):o.kind==='character'?o.sections.map(s=>P.sectionText(s)).join(' '):o.description;return(text||'').trim().split(/\s+/).filter(Boolean).length}
function contextBar(o){const value=o.view.length===P.contexts.length?'all':o.view.length===1?o.view[0]:'custom';return `<div class="context-bar"><span>Used for: <strong>${o.uses.join(' · ')}</strong> ${btn('Change','uses','','tiny')}</span><label>View as <select id="view-select">${[...P.contexts,'custom','all'].map(x=>`<option value="${x}" ${x===value?'selected':''}>${x[0].toUpperCase()+x.slice(1)}</option>`).join('')}</select></label></div>`}
function notes(path,value,label='Private notes'){return `<details class="notes"><summary>${label}${value?' ·':''}</summary><div class="notes-inner"><p>Rough ideas and reminders. Included in backups, excluded from character and manuscript exports.</p><textarea data-bind="${path}" aria-label="${label}">${esc(value)}</textarea></div></details>`}
function content(o,path){if(['Gallery','References'].includes(ui.tab))return media(o,path,ui.tab==='References');if(ui.tab==='Notes'||ui.tab==='Loose pages')return `<p class="section-desc">Thoughts, maybes, and things to come back to. Just for you.</p><div class="page">${input('Private working notes',path+'.notes',o.notes,'textarea','class="freeform"')}</div>`;if(o.kind==='story')return storyContent(o,path);if(o.kind==='project')return projectContent(o,path);
 if(ui.tab==='Setup')return `<p class="section-desc">Public listing information. Your private notes stay separate.</p><div class="page fields">${input('Listing title',path+'.setup.title',o.setup.title,'input',`placeholder="${esc(o.name)}"`)}${input('Chat name',path+'.setup.chatName',o.setup.chatName)}${input('Tagline',path+'.setup.tagline',o.setup.tagline)}${input('Platform tags',path+'.setup.tags',o.setup.tags)}<p class="quiet wide">Platform tags are for publishing. They are excluded from this app’s search and filters.</p><div class="wide">${input('Public introduction — CHub Creator’s Notes / JAI Bio',path+'.setup.publicIntro',o.setup.publicIntro,'textarea')}</div><div class="wide">${input('System prompt',path+'.setup.system',o.setup.system,'textarea')}</div><div class="wide">${input('Post-history instructions',path+'.setup.post',o.setup.post,'textarea')}</div></div>`;
 if(ui.tab==='Connections')return connectionContent(o,path);if(ui.tab==='Greetings'||ui.tab==='Dialogue')return repeats(o,path,ui.tab==='Greetings'?'greetings':'dialogues');
 const s=o.sections.find(x=>x.id===ui.tab),index=o.sections.indexOf(s),sp=path+'.sections.'+index;
 return `<div class="modebar"><div class="segmented">${['Structured','Freeform'].map(m=>btn(m+(m==='Freeform'?s.free.trim()?' ·':'':s.fields.some(f=>f.value.trim())?' ·':''),'mode',m,s.mode===m?'selected':'')).join('')}</div><div class="story-actions">${btn(s.pinned?'★ Unpin':'☆ Pin','pin-section')}${btn(s.collapsed?'Expand':'Collapse','collapse-section')}${btn('Section options','section-options')}</div></div>${s.linkedId||['User / Persona','Partner Character'].includes(s.name)?`<div class="linked-profile"><label>Optional linked character<select id="profile-link"><option value="">No linked book</option>${w.characters.filter(c=>c.id!==o.id).map(c=>`<option value="${c.id}" ${c.id===s.linkedId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>${s.linkedId?btn('Open linked book ↗','open',s.linkedId):''}</div>`:''}${s.collapsed?'<p class="quiet">This section is collapsed. Its writing is preserved.</p>':`<section class="page">${s.mode==='Freeform'?input('Writing',sp+'.free',s.free,'textarea','class="freeform"'):`<div class="fields">${s.fields.map((f,i)=>f.hidden?'':`<div class="field">${input(f.label,sp+'.fields.'+i+'.value',f.value,'textarea')}<div class="field-tools">${reorder('move-field',f.id)}${btn('Options','field-options',f.id,'tiny')}</div></div>`).join('')}</div>${btn('+ Custom field','new-field','','add-field')}${s.fields.some(f=>f.hidden)?btn('Show hidden fields','show-fields','','flat'):''}`}</section>`}${notes(sp+'.notes',s.notes)}`;
}
function repeats(o,path,key){return `<p class="section-desc">${key==='greetings'?'Choose one primary greeting. Labels help you organize; only message text is exported.':'Keep dialogue syntax exactly as you want it to appear in the export.'}</p>${btn('+ Add '+(key==='greetings'?'greeting':'example'),'add-repeat',key,'primary')}${o[key].map((r,i)=>`<section class="page repeat"><div class="story-actions">${reorder('move-repeat',key+':'+r.id)}${key==='greetings'?btn(r.primary?'✓ Primary':'Set primary','primary',r.id):''}${btn('Remove','remove-repeat',key+':'+r.id)}</div>${input('Optional internal label',path+'.'+key+'.'+i+'.label',r.label)}${input('Message text',path+'.'+key+'.'+i+'.text',r.text,'textarea')}</section>`).join('')}`}
function connectionContent(o,path){return `<p class="section-desc">Describe someone, or link their book. Each connection describes this character’s perspective.</p>${btn('+ Add connection','add-connection','','primary')}${o.connections.filter(c=>P.applicable(c.scope,o.view)).map(c=>{const i=o.connections.indexOf(c),cp=path+'.connections.'+i,linked=w.characters.find(b=>b.id===c.linkedId);return `<article class="page repeat"><div class="connection-top"><h2>${esc(linked?.name||c.name||'New connection')}</h2><div>${btn('Applies to: '+(c.scope.length===P.contexts.length?'All':c.scope.join(' + ')),'scope',c.id,'tiny')}${reorder('move-connection',c.id)}${btn('Remove','remove-connection',c.id,'tiny')}</div></div><label>Linked character<select data-bind="${cp}.linkedId"><option value="">Describe here</option>${w.characters.filter(b=>b.id!==o.id).map(b=>`<option value="${b.id}" ${b.id===c.linkedId?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label>${linked?`<div class="story-actions">${btn('Open book ↗','open',linked.id)}${btn('Add reciprocal connection','reciprocal',c.id)}</div>`:input('Name',cp+'.name',c.name)}${input('Relationship',cp+'.relationship',c.relationship)}${input('Description / dynamic',cp+'.description',c.description,'textarea')}${c.custom.map((f,j)=>`<div class="custom-row">${input(f.label,cp+'.custom.'+j+'.value',f.value,'textarea')}${btn('Remove field','remove-connection-field',c.id+':'+j,'tiny')}</div>`).join('')}${btn('+ Custom field','connection-field',c.id,'flat')}${notes(cp+'.notes',c.notes,'Private connection notes')}</article>`}).join('')}`}
function media(o,path,reference){const key=reference?'references':'gallery',items=o[key];return `<p class="section-desc">${reference?'Inspiration and research. References are separate from character facts and story writing.':'Images of your '+(o.kind==='character'?'character':o.kind==='story'?'story':'Project')+'. Choose any image as a cover; the original stays unchanged.'}</p><div class="story-actions">${btn('+ Add images','add-image',key,'primary')}${reference?btn('+ Text reference','text-reference'):''}</div><div class="gallery">${items.map((a,i)=>`<article class="page media-card">${a.type==='image'?`<button class="image-open" data-action="view-image" data-value="${key}:${a.id}"><img src="${a.data}" alt="${esc(a.title||'Untitled image')}"></button>`:input('Reference text',path+'.'+key+'.'+i+'.text',a.text,'textarea')}${input('Optional title',path+'.'+key+'.'+i+'.title',a.title)}${input('Optional description',path+'.'+key+'.'+i+'.description',a.description,'textarea')}${reference?input('Optional source URL',path+'.'+key+'.'+i+'.source',a.source||''):''}<div class="story-actions">${reorder('move-media',key+':'+a.id)}${!reference?`${btn('Use as cover','cover',a.id)}${o.kind==='character'?btn(o.portraitId===a.id?'✓ Portrait':'Use as portrait','portrait',a.id):''}`:''}${btn('Remove','remove-media',key+':'+a.id)}</div></article>`).join('')}</div>`}
function storyContent(o,path){if(ui.tab==='Characters')return `<p class="section-desc">Link the cast without duplicating their character books.</p><div class="story-actions">${btn('Manage cast','cast','','primary')}${btn('+ New character','create','characters')}</div>${o.cast.map((entry,i)=>{const c=w.characters.find(c=>c.id===entry.characterId);return `<div class="page repeat"><div class="connection-top"><h2>${esc(c?.name||'Unavailable character')}</h2><div>${c?btn('Open book','open',c.id)+btn('Quick reference','cast-reference',c.id):''}${btn('Remove from cast','remove-cast',entry.characterId)}</div></div>${input('Role in this story',path+'.cast.'+i+'.role',entry.role)}</div>`}).join('')}`;
 if(!o.chapters.length)o.chapters.push({id:P.uid(),title:'',text:''});let chapter=o.chapters.find(c=>c.id===ui.chapter)||o.chapters[0];ui.chapter=chapter.id;const i=o.chapters.indexOf(chapter);return `<div class="writing-tools"><label>Chapter / scene<select id="chapter-select">${o.chapters.map((c,i)=>`<option value="${c.id}" ${c.id===chapter.id?'selected':''}>${esc(c.title||'Part '+(i+1))}</option>`).join('')}</select></label>${btn('+ Add part','add-chapter')}${reorder('move-chapter',chapter.id)}${o.chapters.length>1?btn('Remove part','remove-chapter',chapter.id):''}</div><div class="page">${input('Optional chapter or scene title',path+'.chapters.'+i+'.title',chapter.title)}<div class="writing-tools">${btn('Bold','format','bold','tiny')}${btn('Italic','format','italic','tiny')}${btn('Heading','format','heading','tiny')}${btn('Scene break','format','break','tiny')}${btn('Reading preview','preview-writing','','tiny')}</div><textarea class="manuscript" id="manuscript" data-bind="${path}.chapters.${i}.text" aria-label="Story writing">${esc(chapter.text)}</textarea><p class="quiet">Plain-text writing with Markdown formatting. No images in text fields.</p></div>`}
function projectContent(o,path){if(ui.tab==='Connections'){const list=w.characters.filter(c=>o.members.includes(c.id));return `<p class="section-desc">Connections from characters in this Project. Arrows describe each character’s perspective.</p><div class="page">${list.flatMap(c=>c.connections.map(link=>{const target=w.characters.find(b=>b.id===link.linkedId);return `<p>${btn(esc(c.name),'open',c.id,'flat')} → ${target?btn(esc(target.name),'open',target.id,'flat'):esc(link.name||'Unnamed')} — ${esc(link.relationship||'Connection')} <small>${esc(link.scope.join(' · '))}</small></p>`})).join('')||'<p>No connections yet.</p>'}</div>`}
 return `<div class="page">${input('Optional Project description',path+'.description',o.description,'textarea')}<div class="story-actions">${btn('Manage contents','project-members','','primary')}${btn('+ New character','create','characters')}${btn('+ New Story','create','stories')}</div></div><h2>Characters</h2><div class="books">${w.characters.filter(c=>o.members.includes(c.id)).map(c=>`<button class="book-button" data-action="open" data-value="${c.id}">${cover(c)}</button>`).join('')}</div><h2>Stories</h2><div class="books">${w.stories.filter(s=>o.stories.includes(s.id)).map(s=>`<button class="book-button" data-action="open" data-value="${s.id}">${cover(s)}</button>`).join('')}</div>`}
function render(){document.body.classList.toggle('dark',w.settings.dark);$('#app').innerHTML=header()+(object()?shell(object()):library());bind($('#app'));status()}
function bind(root){root.querySelectorAll('[data-action]').forEach(el=>el.onclick=e=>{e.preventDefault();Promise.resolve(action(el.dataset.action,el.dataset.value)).catch(err=>notice(err.message))});root.querySelectorAll('[data-bind]').forEach(el=>{if(el.dataset.boundInput)return;el.dataset.boundInput='yes';const event=el.tagName==='SELECT'||el.type==='checkbox'?'change':'input';el.addEventListener(event,()=>{checkpoint(event==='input');set(el.dataset.bind,el.type==='checkbox'?el.checked:el.value);changed();const count=$('#word-count');if(count&&object())count.textContent=wordCount(object())+' words';if(event==='change'&&!modal.contains(el))render()})});
 const search=root.querySelector('#library-search');if(search)search.oninput=()=>{const start=search.selectionStart;ui.query=search.value;render();$('#library-search').focus();$('#library-search').setSelectionRange(start,start)};
 const view=root.querySelector('#view-select');if(view)view.onchange=()=>{if(view.value==='custom')chooseContexts('view');else transact(()=>object().view=view.value==='all'?P.contexts.slice():[view.value])};
 const link=root.querySelector('#profile-link');if(link)link.onchange=()=>transact(()=>object().sections.find(s=>s.id===ui.tab).linkedId=link.value);
 const chapter=root.querySelector('#chapter-select');if(chapter)chapter.onchange=()=>navigate(()=>{ui.chapter=chapter.value});
}
function askName(title,callback,initial=''){dialog(title,`<label>Name<input id="name-value" value="${esc(initial)}" maxlength="150"></label>`,[['Cancel','close-modal'],['Save','submit-name','','primary']]);$('#name-value').focus();$('#name-value').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#modal [data-action="submit-name"]').click()}};$('#modal [data-action="submit-name"]').onclick=()=>{const value=$('#name-value').value.trim();if(!value){$('#name-value').focus();return}closeDialog();callback(value)}}
function confirmAction(title,text,callback){dialog(title,`<p>${esc(text)}</p>`,[['Cancel','close-modal'],['Confirm','confirm-action','','primary']]);$('#modal [data-action="confirm-action"]').onclick=()=>{closeDialog();callback()}}
function chooseContexts(type,id){const o=object(),c=o.connections.find(c=>c.id===id),value=type==='scope'?c.scope:o[type];dialog(type==='scope'?'Applies to':type==='view'?'View contexts':'Used for',`<p>Select the contexts to include. Existing writing is never deleted.</p>${P.contexts.map(x=>`<label class="check"><input name="ctx" type="checkbox" value="${x}" ${value.includes(x)?'checked':''}>${x[0].toUpperCase()+x.slice(1)}</label>`).join('')}`,[['Apply','apply-context','','primary']]);$('#modal [data-action="apply-context"]').onclick=()=>{const selected=[...modal.querySelectorAll('[name=ctx]:checked')].map(el=>el.value);if(!selected.length)return;transact(()=>{if(type==='scope')c.scope=selected;else o[type]=selected});closeDialog()}}
async function imageFiles(key){const picker=$('#file-picker');picker.accept='image/png,image/jpeg,image/webp,image/gif';picker.multiple=true;picker.value='';const owner=object();picker.onchange=async()=>{try{const files=[...picker.files];const results=[];for(const file of files){if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type))throw Error('Use PNG, JPEG, WebP, or GIF images.');if(file.size>8*1024*1024)throw Error('Each image must be under 8 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not read image.'));reader.readAsDataURL(file)});await new Promise((resolve,reject)=>{const img=new Image();img.onload=resolve;img.onerror=()=>reject(Error('This file is not a readable image.'));img.src=data});results.push({id:P.uid(),type:'image',title:'',description:'',source:'',data})}transact(()=>owner[key].push(...results))}catch(e){notice(e.message)}};picker.click()}
function bookOptions(){const o=object();dialog('Book options',`<p>${esc(o.name)}</p><div class="option-grid">${btn('Rename','rename-book')}${btn(o.archived?'Unarchive':'Archive','archive')}${btn('Cover & color','book-cover')}${o.kind==='character'?btn('Save structure as template','template'):''}${btn(o.snapshot?'Replace protected snapshot':'Create protected snapshot','snapshot')}${o.snapshot?`${btn('Inspect / restore snapshot','inspect-snapshot')}<p class="quiet">${esc(o.snapshot.label)} · ${new Date(o.snapshot.date).toLocaleString()}</p>`:''}</div>`)}
function coverDialog(id){const o=object(),a=o.gallery.find(a=>a.id===(id||o.cover?.id));dialog('Book cover',`<div class="cover-config"><div>${cover(o)}</div><div><label>Cover color<input id="cover-color" type="color" value="${o.color}"></label><label>Image<select id="cover-image"><option value="">Default cover</option>${o.gallery.map((a,i)=>`<option value="${a.id}" ${a.id===(id||o.cover?.id)?'selected':''}>${esc(a.title||'Image '+(i+1))}</option>`).join('')}</select></label><label>Horizontal position<input id="cover-x" type="range" min="0" max="100" value="${o.cover?.x??50}"></label><label>Vertical position<input id="cover-y" type="range" min="0" max="100" value="${o.cover?.y??50}"></label><label>Zoom<input id="cover-zoom" type="range" min="1" max="3" step="0.05" value="${o.cover?.zoom??1}"></label><p class="quiet">Your original gallery image stays unchanged.</p></div></div>` ,[['Apply cover','apply-cover','','primary']]);
 const preview=()=>{const temp={...o,color:$('#cover-color').value,cover:$('#cover-image').value?{id:$('#cover-image').value,x:+$('#cover-x').value,y:+$('#cover-y').value,zoom:+$('#cover-zoom').value}:null};$('#modal .cover-config>div').innerHTML=cover(temp)};modal.querySelectorAll('input,select').forEach(el=>el.oninput=preview);preview();$('#modal [data-action="apply-cover"]').onclick=()=>{transact(()=>{o.color=$('#cover-color').value;o.cover=$('#cover-image').value?{id:$('#cover-image').value,x:+$('#cover-x').value,y:+$('#cover-y').value,zoom:+$('#cover-zoom').value}:null});closeDialog()}}
function manageMembers(kind){const o=object(),project=kind==='project';dialog(project?'Project contents':'Story cast',`<p>Link existing books. Removing a link never deletes its book.</p><div class="dialog-list"><h3>Characters</h3>${w.characters.map(c=>`<label class="check"><input type="checkbox" name="member" value="${c.id}" ${(project?o.members.includes(c.id):o.cast.some(x=>x.characterId===c.id))?'checked':''}>${esc(c.name)}${c.archived?' (archived)':''}</label>`).join('')}${project?`<h3>Stories</h3>${w.stories.map(s=>`<label class="check"><input type="checkbox" name="story" value="${s.id}" ${o.stories.includes(s.id)?'checked':''}>${esc(s.name)}</label>`).join('')}`:''}</div>`,[['Save links','save-members','','primary']]);$('#modal [data-action="save-members"]').onclick=()=>{const ids=[...modal.querySelectorAll('[name=member]:checked')].map(el=>el.value);transact(()=>{if(project){o.members=ids;o.stories=[...modal.querySelectorAll('[name=story]:checked')].map(el=>el.value)}else o.cast=ids.map(id=>o.cast.find(c=>c.characterId===id)||{characterId:id,role:''})});closeDialog()}}
function markdown(text){return esc(text).split('\n').map(line=>/^#{1,3} /.test(line)?'<h3>'+line.replace(/^#+ /,'')+'</h3>':line==='---'?'<hr>':'<p>'+line.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>')+'</p>').join('')}
let pendingImport=null,exportOptions=null;
function exportDialog(){const o=object();if(o.kind==='story'){const text=o.name+'\n\n'+o.chapters.map(c=>[c.title,c.text].filter(Boolean).join('\n\n')).join('\n\n');dialog('Export manuscript',`<p>Includes only the title and writing, in chapter order. References, galleries, cast details, and private notes stay out. Markdown emphasis is preserved in this text file.</p><textarea id="export-output" readonly>${esc(text)}</textarea>`,[['Copy manuscript','copy-export'],['Download .txt','download-manuscript','','primary']]);return}
 exportOptions={...{target:'bio',context:'story',representation:'both',layout:'separate',links:[]},...o.exportPrefs};renderExport();}
function renderExport(){const o=object(),p=exportOptions;const out=P.exportCharacter(o,w,p);const ids=new Set([...o.connections.filter(c=>P.applicable(c.scope,p.target==='bio'?(p.context==='all'?P.contexts:[p.context]):['chatbot'])).map(c=>c.linkedId),...o.sections.filter(s=>P.applicable(s.scope,p.target==='bio'?(p.context==='all'?P.contexts:[p.context]):['chatbot'])).map(s=>s.linkedId)].filter(Boolean));
 const sel=(key,label,options)=>`<label>${label}<select data-export="${key}">${options.map(([v,t])=>`<option value="${v}" ${p[key]===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
 dialog('Export character',`<div class="fields">${sel('target','Destination',[['bio','Detailed Character Bio (.txt)'],['chub','CHub / Venus — V2 JSON'],['silly','SillyTavern — V2 JSON'],['jai','JanitorAI — copy fields']])}${p.target==='bio'?sel('context','Export context',[['story','Story'],['chatbot','Chatbot'],['roleplay','Roleplay'],['game','Game'],['all','All']]):'<p>Export context: <strong>Chatbot</strong></p>'}${sel('representation','Section content',[['both','Structured and Freeform'],['structured','Structured only'],['freeform','Freeform only']])}${p.target!=='bio'?sel('layout','Definition layout',[['separate','Separate destination fields'],['combined','Combined definition']]):''}</div>${[...ids].length?`<details><summary>Include linked character details (optional)</summary><p>Only the selected books’ applicable character facts are added. Their private notes and further links are excluded.</p>${[...ids].map(id=>{const linked=w.characters.find(c=>c.id===id);return linked?`<label class="check"><input data-export-link="${id}" type="checkbox" ${p.links.includes(id)?'checked':''}>${esc(linked.name)}</label>`:''}).join('')}</details>`:''}<p class="inspector">${out.stats.included} content items included · ${out.stats.empty} empty entries omitted · ${out.stats.excluded} items excluded by context.<br>Private notes, references, gallery data, and snapshots excluded.</p>
 ${p.target==='jai'?`<p>Copy each field into JanitorAI. General author instructions are included in Personality; explicit system/post-history overrides have no matching field in this supplied layout.</p>${out.tooMany?'<p class="banner">Select at most 10 initial messages below before downloading.</p>':''}<div class="export-fields">${Object.entries(out.fields).map(([key,value],i)=>`<label>${esc(key)}<textarea readonly id="copy-field-${i}">${esc(value)}</textarea>${btn('Copy '+esc(key),'copy-field',String(i),'tiny')}</label>`).join('')}</div><h3>Initial messages</h3>${o.greetings.filter(g=>g.text.trim()).map(g=>`<label class="check"><input data-greeting-export="${g.id}" type="checkbox" ${!p.greetingIds||p.greetingIds.includes(g.id)?'checked':''}>${esc(g.label||'Untitled greeting')}</label>`).join('')}${out.greetings.map((g,i)=>`<label>Initial message ${i+1}<textarea readonly id="greeting-copy-${i}">${esc(g.text)}</textarea>${btn('Copy message','copy-greeting',String(i),'tiny')}</label>`).join('')}`:`${out.metadata?'<p class="banner">V2 JSON uses a documented shared character format. Tagline and In-Chat Name are preserved in an extension; CHub’s import of those two listing fields is unverified. Copy them into the site if needed.</p>'+Object.entries(out.metadata).map(([key,value],i)=>`<label>${esc(key)}<textarea readonly id="metadata-${i}">${esc(value)}</textarea>${btn('Copy','copy-metadata',String(i),'tiny')}</label>`).join(''):''}<textarea id="export-output" readonly spellcheck="false">${esc(out.text)}</textarea>`}
 <p class="quiet">Preview shows the exact output. Export settings are remembered with this character. Exported JSON does not embed the selected portrait; download that image separately from Gallery.</p>`,[['Close','close-modal'],...(p.target==='jai'?[]:[['Copy export','copy-export']]),['Download','download-export','','primary']]);
 const dual=o.sections.filter(s=>s.free.trim()&&s.fields.some(f=>f.value.trim()));if(dual.length){const perSection=document.createElement('details');perSection.innerHTML='<summary>Choose content per section</summary><p>Override the general choice where both versions contain writing.</p>'+dual.map(s=>`<label>${esc(s.name)}<select data-section-export="${s.id}">${[['','Use general choice'],['both','Both versions'],['structured','Structured only'],['freeform','Freeform only']].map(([key,label])=>`<option value="${key}" ${(p.sectionRepresentations?.[s.id]||'')===key?'selected':''}>${label}</option>`).join('')}</select></label>`).join('');modal.querySelector('.inspector').before(perSection);perSection.querySelectorAll('select').forEach(el=>el.onchange=()=>{p.sectionRepresentations??={};p.sectionRepresentations[el.dataset.sectionExport]=el.value;rememberExport();renderExport()})}
 modal.querySelectorAll('[data-export]').forEach(el=>el.onchange=()=>{p[el.dataset.export]=el.value;rememberExport();renderExport()});modal.querySelectorAll('[data-export-link]').forEach(el=>el.onchange=()=>{p.links=[...modal.querySelectorAll('[data-export-link]:checked')].map(e=>e.dataset.exportLink);rememberExport();renderExport()});modal.querySelectorAll('[data-greeting-export]').forEach(el=>el.onchange=()=>{p.greetingIds=[...modal.querySelectorAll('[data-greeting-export]:checked')].map(e=>e.dataset.greetingExport);rememberExport();renderExport()});}
function rememberExport(){object().exportPrefs=P.clone(exportOptions);changed()}
async function copyText(text){try{await navigator.clipboard.writeText(text);const msg=document.createElement('p');msg.className='copy-feedback';msg.textContent='Copied';modal.append(msg);setTimeout(()=>msg.remove(),1500)}catch{const area=modal.querySelector('textarea');if(area){area.focus();area.select()}notice('Clipboard access was blocked. Select the export text and copy it manually.')}}
async function action(name,value){const o=object(),path=objectPath(),s=o?.sections?.find(s=>s.id===ui.tab);
 switch(name){
 case 'close-modal':return closeDialog();
 case 'save':return save();
 case 'backup':return fullBackup();
 case 'save-leave':{const next=afterModal;if(await save()){closeDialog();next?.();render()}return}
 case 'discard':{const next=afterModal;w=P.clone(saved);dirty=false;generation++;undo=[];redo=[];clearTimeout(timer);closeDialog();next?.();render();return}
 case 'undo':if(undo.length){redo.push(P.clone(w));w=undo.pop();changed();render()}return;
 case 'redo':if(redo.length){undo.push(P.clone(w));w=redo.pop();changed();render()}return;
 case 'theme':return transact(()=>w.settings.dark=!w.settings.dark);
 case 'home':return navigate(()=>{ui.id=null;ui.focus=false;ui.query='' });
 case 'library':return navigate(()=>{ui.id=null;ui.page=value;ui.query='';ui.archive=false});
 case 'open':return openItem(value);
 case 'tab':return navigate(()=>{ui.tab=value});
 case 'filter':ui.filter=value;render();return;
 case 'toggle-archive':ui.archive=!ui.archive;render();return;
 case 'focus':ui.focus=!ui.focus;render();return;
 case 'show-empty':ui.showEmpty=!ui.showEmpty;render();return;
 case 'uses':return chooseContexts('uses');
 case 'scope':return chooseContexts('scope',value);
 case 'mode':return transact(()=>s.mode=value);
 case 'pin-section':return transact(()=>s.pinned=!s.pinned);
 case 'collapse-section':return transact(()=>s.collapsed=!s.collapsed);
 case 'create':{
 const owner=o;dialog('New '+(value==='characters'?'Character Paper':value==='stories'?'Story':'Project'),`<label>Name<input id="new-name" maxlength="150" required></label>${value==='characters'?`<label>Template<select id="new-template"><option value="">Default structure</option>${w.templates.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label>`:''}`,[['Cancel','close-modal'],['Create','create-confirm','','primary']]);$('#new-name').focus();const submit=()=>{const name=$('#new-name').value.trim();if(!name)return;const t=w.templates.find(t=>t.id===$('#new-template')?.value);transact(()=>{const item=value==='characters'?(t?P.fromTemplate(t,name):P.character(name)):value==='stories'?P.story(name):P.project(name);item.color=colors[w[value].length%colors.length];w[value].push(item);if(owner?.kind==='project'){if(value==='characters')owner.members.push(item.id);if(value==='stories')owner.stories.push(item.id)}if(owner?.kind==='story'&&value==='characters')owner.cast.push({characterId:item.id,role:''});ui.id=item.id;ui.tab=item.kind==='character'?'Loose pages':item.kind==='story'?'Writing':'Contents';ui.chapter=null});closeDialog()};$('#modal [data-action="create-confirm"]').onclick=submit;$('#new-name').onkeydown=e=>{if(e.key==='Enter')submit()};return}
 case 'book-options':return bookOptions();
 case 'rename-book':return askName('Rename book',name=>transact(()=>o.name=name),o.name);
 case 'archive':closeDialog();return transact(()=>{o.archived=!o.archived;ui.id=null});
 case 'unarchive':return transact(()=>{[...w.characters,...w.projects,...w.stories].find(x=>x.id===value).archived=false});
 case 'book-cover':return coverDialog();
 case 'cover':return coverDialog(value);
 case 'portrait':return transact(()=>o.portraitId=value);
 case 'snapshot':return askName(o.snapshot?'Replace protected snapshot':'Create protected snapshot',label=>{const create=async()=>{transact(()=>o.snapshot=P.makeSnapshot(o,label));await save()};if(o.snapshot)confirmAction('Replace snapshot?','This replaces your one protected checkpoint. Ordinary saves never do this.',create);else create()});
 case 'inspect-snapshot':{const snap=o.snapshot;const text=snap.data.kind==='character'?P.exportCharacter(snap.data,w,{target:'bio',context:'all'}).text:snap.data.kind==='story'?snap.data.chapters.map(c=>c.title+'\n'+c.text).join('\n\n'):snap.data.description;dialog('Protected snapshot',`<h3>${esc(snap.label)}</h3><p>${new Date(snap.date).toLocaleString()} · ${snap.data.gallery.length} gallery images · ${snap.data.references.length} references</p><p>Restore replaces this book’s details, notes, images, and links. Other books remain unchanged. The snapshot remains protected.</p><textarea readonly>${esc(text)}</textarea>`,[['Cancel','close-modal'],['Restore snapshot','restore-snapshot','','primary']]);return}
 case 'restore-snapshot':return confirmAction('Restore this snapshot?','Your current book will be replaced. You can undo this during the current session.',()=>{transact(()=>{set(path,P.restoreSnapshot(o))});save()});
 case 'template':return askName('Save structure as template',name=>transact(()=>w.templates.push(P.makeTemplate(o,name))));
 case 'new-section':return askName('New custom section',name=>transact(()=>{const section=P.section(name,[],true);o.sections.push(section);ui.tab=section.id}));
 case 'new-field':return askName('Custom field label',label=>transact(()=>s.fields.push({id:P.uid(),label,value:'',custom:true,hidden:false})));
 case 'show-fields':return transact(()=>s.fields.forEach(f=>f.hidden=false));
 case 'section-options':return dialog('Section options',`<p>${esc(s.name)}</p><div class="story-actions">${reorder('move-section',s.id)}${btn('Rename','rename-section')}${btn('Remove section','remove-section')}</div><p class="quiet">Removing a section can be undone during this session.</p>`);
 case 'rename-section':return askName('Rename section',name=>transact(()=>s.name=name),s.name);
 case 'remove-section':return confirmAction('Remove section?', 'This removes its fields and notes. Undo or your protected snapshot can recover them.',()=>transact(()=>{o.sections=o.sections.filter(x=>x.id!==s.id);ui.tab='Loose pages'}));
 case 'move-section':{const [id,d]=value.split(':');transact(()=>move(o.sections,o.sections.findIndex(s=>s.id===id),+d));return}
 case 'move-field':{const [id,d]=value.split(':');return transact(()=>move(s.fields,s.fields.findIndex(f=>f.id===id),+d))}
 case 'field-options':{const f=s.fields.find(f=>f.id===value);return dialog('Field options',`<p>${esc(f.label)}</p><div class="story-actions">${btn('Hide field','hide-field',f.id)}${f.custom?btn('Rename','rename-field',f.id)+btn('Remove','remove-field',f.id):''}</div>`)}
 case 'hide-field':closeDialog();return transact(()=>s.fields.find(f=>f.id===value).hidden=true);
 case 'rename-field':{const f=s.fields.find(f=>f.id===value);return askName('Field label',name=>transact(()=>f.label=name),f.label)}
 case 'remove-field':return confirmAction('Remove field?','The field and its text will be removed. You can undo this during the session.',()=>transact(()=>s.fields=s.fields.filter(f=>f.id!==value)));
 case 'add-repeat':return transact(()=>o[value].push({id:P.uid(),label:'',text:'',primary:value==='greetings'&&!o[value].length}));
 case 'primary':return transact(()=>o.greetings.forEach(g=>g.primary=g.id===value));
 case 'move-repeat':{const [key,id,d]=value.split(':');return transact(()=>move(o[key],o[key].findIndex(x=>x.id===id),+d))}
 case 'remove-repeat':{const [key,id]=value.split(':');return confirmAction('Remove entry?','Its writing will be removed. You can undo this during the session.',()=>transact(()=>{o[key]=o[key].filter(x=>x.id!==id)}))}
 case 'add-connection':return transact(()=>o.connections.push({id:P.uid(),name:'',linkedId:'',relationship:'',description:'',notes:'',scope:P.contexts.slice(),custom:[]}));
 case 'remove-connection':return confirmAction('Remove connection?','Only this connection is removed. Linked character books remain.',()=>transact(()=>o.connections=o.connections.filter(c=>c.id!==value)));
 case 'move-connection':{const [id,d]=value.split(':');return transact(()=>move(o.connections,o.connections.findIndex(c=>c.id===id),+d))}
 case 'connection-field':return askName('Custom connection field',label=>transact(()=>o.connections.find(c=>c.id===value).custom.push({id:P.uid(),label,value:''})));
 case 'remove-connection-field':{const [id,index]=value.split(':');return transact(()=>o.connections.find(c=>c.id===id).custom.splice(+index,1))}
 case 'reciprocal':{const c=o.connections.find(c=>c.id===value),target=w.characters.find(b=>b.id===c.linkedId);return askName('Relationship from '+target.name+' to '+o.name,label=>confirmAction('Add reciprocal connection?',`This will add a separate connection in ${target.name}. Feelings and descriptions are not copied.`,()=>transact(()=>target.connections.push({id:P.uid(),name:o.name,linkedId:o.id,relationship:label,description:'',notes:'',scope:c.scope.slice(),custom:[]}))),c.relationship)}
 case 'add-image':return imageFiles(value);
 case 'text-reference':return transact(()=>o.references.push({id:P.uid(),type:'text',title:'',description:'',text:'',source:''}));
 case 'view-image':{const [key,id]=value.split(':'),a=o[key].find(x=>x.id===id);dialog(a.title||'Image',`<img class="full-image" src="${a.data}" alt="${esc(a.title||'Image')}"><p>${esc(a.description)}</p>`,[['Download original','download-image',value]]);return}
 case 'download-image':{const [key,id]=value.split(':'),a=o[key].find(x=>x.id===id);const link=document.createElement('a');link.href=a.data;link.download=safeName(a.title||'image')+'.'+a.data.split(';')[0].split('/')[1];link.click();return}
 case 'move-media':{const [key,id,d]=value.split(':');return transact(()=>move(o[key],o[key].findIndex(a=>a.id===id),+d))}
 case 'remove-media':{const [key,id]=value.split(':');return confirmAction('Remove this item?',`${o.cover?.id===id?'It is used as the cover; the default cover will return. ':''}${o.portraitId===id?'The exported portrait selection will be cleared. ':''}Protected snapshots retain their copy. You can undo this removal.`,()=>transact(()=>{o[key]=o[key].filter(a=>a.id!==id);if(o.cover?.id===id)o.cover=null;if(o.portraitId===id)o.portraitId=''}))}
 case 'cast':return manageMembers('cast');
 case 'project-members':return manageMembers('project');
 case 'remove-cast':return transact(()=>o.cast=o.cast.filter(c=>c.characterId!==value));
 case 'cast-reference':{const c=w.characters.find(c=>c.id===value);return dialog(c.name,`<div class="reading">${c.sections.filter(s=>['Information','Appearance','Personality'].includes(s.name)).map(s=>`<h3>${esc(s.name)}</h3><p>${esc(P.sectionText(s)).replace(/\n/g,'<br>')}</p>`).join('')}</div>`)}
 case 'add-chapter':return askName('Chapter or scene name',title=>transact(()=>{const c={id:P.uid(),title,text:''};o.chapters.push(c);ui.chapter=c.id}));
 case 'move-chapter':{const [id,d]=value.split(':');return transact(()=>move(o.chapters,o.chapters.findIndex(c=>c.id===id),+d))}
 case 'remove-chapter':return confirmAction('Remove this writing part?','Its text will be removed. You can undo this during the session.',()=>transact(()=>{o.chapters=o.chapters.filter(c=>c.id!==value);ui.chapter=null}));
 case 'format':{const el=$('#manuscript'),start=el.selectionStart,end=el.selectionEnd,text=el.value.slice(start,end);const insert=value==='bold'?'**'+text+'**':value==='italic'?'*'+text+'*':value==='heading'?'\n## '+text:'\n\n---\n\n';checkpoint();el.setRangeText(insert,start,end,'select');set(el.dataset.bind,el.value);changed();el.focus();return}
 case 'preview-writing':return dialog('Reading preview',`<div class="reading">${o.chapters.map(c=>'<h2>'+esc(c.title)+'</h2>'+markdown(c.text)).join('')}</div>`);
 case 'export':return exportDialog();
 case 'copy-export':return copyText($('#export-output').value);
 case 'copy-field':return copyText($('#copy-field-'+value).value);
 case 'copy-greeting':return copyText($('#greeting-copy-'+value).value);
 case 'copy-metadata':return copyText($('#metadata-'+value).value);
 case 'download-manuscript':return download(safeName(o.name)+'.txt',$('#export-output').value,'text/plain;charset=utf-8');
 case 'download-export':{const result=P.exportCharacter(o,w,exportOptions);if(result.tooMany)return notice('Choose at most ten initial messages before downloading the JanitorAI field sheet.');rememberExport();const text=exportOptions.target==='jai'?[...Object.entries(result.fields).map(([k,v])=>k+'\n'+v),...result.greetings.map((g,i)=>'Initial message '+(i+1)+'\n'+g.text)].join('\n\n'):result.text;return download(safeName(o.name)+(result.card?'.json':'.txt'),text,result.card?'application/json':'text/plain;charset=utf-8')}
 case 'settings':return dialog('Saving & preferences',`<p>${native?'This review build saves to the data folder beside the app. Keep that folder with the app.':'Browser mode saves to IndexedDB on this device. Use the included launcher for local-file saving.'}</p><label>Saving mode<select id="saving-mode"><option value="auto" ${w.settings.autosave?'selected':''}>Autosave</option><option value="manual" ${!w.settings.autosave?'selected':''}>Manual</option></select></label><label class="check"><input id="collapse-setting" type="checkbox" ${w.settings.collapseEmpty?'checked':''}>Minimize unused sections</label><p>Autosave runs after a typing pause, during long editing, and when leaving a book. Manual mode shows Save and asks before discarding changes.</p><p>Shortcuts: Ctrl/Cmd+S save · Ctrl/Cmd+Z undo · Ctrl/Cmd+Shift+Z redo · Ctrl/Cmd+K search · Ctrl/Cmd+N new character.</p>`,[['Apply','apply-settings','','primary']]);
 case 'apply-settings':{const auto=$('#saving-mode').value==='auto',collapse=$('#collapse-setting').checked;transact(()=>{w.settings.autosave=auto;w.settings.collapseEmpty=collapse});closeDialog();await save();return}
 case 'import':{const picker=$('#file-picker');picker.accept='.json,application/json';picker.multiple=false;picker.value='';picker.onchange=async()=>{try{const file=picker.files[0];if(!file)return;if(file.size>150*1024*1024)throw Error('Backup exceeds the 150 MB limit.');pendingImport=P.migrate(JSON.parse(await file.text()));dialog('Restore full backup',`<p>This backup contains ${pendingImport.characters.length} characters, ${pendingImport.stories.length} Stories, and ${pendingImport.projects.length} Projects, including their private notes, images, and protected snapshots.</p><p>This replaces the current library. Download your current backup first if you want to keep it.</p>`,[['Download current backup','backup'],['Cancel','close-modal'],['Replace library','apply-import','','primary']])}catch(e){notice(e.message)}};picker.click();return}
 case 'apply-import':if(pendingImport){const before=P.clone(w);transact(()=>{w=pendingImport;ui.id=null;ui.page='characters'});closeDialog();if(await save()){pendingImport=null;undo=[];redo=[];notice('Backup restored and saved.')}else{w=before;dirty=true;render();notice('Restore could not be saved. Your original library is still available; download a backup before retrying.')}}return;
 case 'about':return dialog('About the app & creator',`<h3>About the app</h3><p>Character Paper is a tool for authors, writers, and creators to write and organize their characters and stories. A place for every character.</p><p><strong>Character Paper is completely free to use, and it will remain free.</strong></p><p>v1.0.2 review build · no account, cloud sync, or AI requests.</p><h3>Frequently asked questions</h3>${[
 ['What are Projects?','Optional groups containing characters, Stories, or both. Characters may belong to multiple Projects. Stories link their cast without duplicating character books.'],
 ['What do contexts do?','Used for controls library filtering. View as shows Chatbot, Roleplay, Story, Custom, or All sections. Connection scope controls viewing and exporting. Hidden writing is preserved.'],
 ['Can I organize my own sections?','Create custom sections and fields, reorder with arrows, pin sections, hide fields, minimize unused sections, or enter focus mode. Structure-only templates exclude facts, notes, links, and images.'],
 ['Where do images and references go?','Gallery contains your character or story images with optional titles and descriptions. References hold text or images for inspiration, with optional source URLs. Text fields contain no images. Choose and crop a gallery image as a cover without changing the original; portrait selection is separate.'],
 ['How do saves and snapshots work?','Choose autosave or manual saving. The bottom indicator reports real save status. Create one protected snapshot from Book options; it changes only when you explicitly replace it. Local-file mode retains a last-good recovery copy. Unsaved edits may be lost in a crash. Full backups protect against loss of the device.'],
 ['What is included in exports?','The preview filters context, assembles selected structured/freeform content, and excludes private notes, references, images, snapshots, and empty content. Required V2 fields remain present even when blank. Linked character facts are included only when selected. Platform tags are not searched inside the app.'],
 ['What can I write in Stories?','Continuous text or reordered chapters/scenes, with light Markdown formatting and reading preview. The cast, references, gallery, and private notes have separate tabs. Manuscript export includes only writing.'],
 ['What remains for launch?','Desktop installer packaging and v1.0.2 release testing. CHub listing metadata import needs a real-site compatibility check; the two fields can be copied separately. Shared Project lore, cloud sync, and Android are deferred.']
 ].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}<h3>About the creator</h3><p>Created by <strong>Hebi4u</strong>.</p>`);
 }
}
document.addEventListener('click',e=>{const target=e.target.closest('#save-status [data-action]');if(target)action(target.dataset.action,target.dataset.value)});
window.addEventListener('beforeunload',e=>{if(dirty||saving){e.preventDefault();e.returnValue=''}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&w.settings.autosave&&dirty)save()});
setInterval(()=>{if(w.settings.autosave&&dirty)save()},10000);
async function start(){try{let initial=null,recovered=false,loadError='';
 if(location.protocol.startsWith('http')){try{const r=await fetch('/api/library');if(r.status===404){native=false}else{const result=await r.json();if(!r.ok)throw Error(result.error||'Could not open local library.');native=true;token=result.token;revision=result.revision;initial=result.state;recovered=result.recovered;loadError=result.loadError||''}}catch(e){if(e.message.includes('Saved library')||e.message.includes('Unexpected'))throw e;throw Error('Local save service is unavailable. Start the included launcher, then reload.')}}
 if(loadError){saved=P.clone(w);throw Error(loadError)}
 if(!native){db=await idbOpen();initial=await idbGet()}
 let migrated=false;if(initial)w=P.migrate(initial);else{let legacy=null;try{const chars=JSON.parse(localStorage.getItem('bible-prototype-books'));if(Array.isArray(chars))legacy={characters:chars,stories:JSON.parse(localStorage.getItem('paper-stories'))||[],theme:localStorage.getItem('bible-theme')}}catch{}if(legacy){w=P.migrate(legacy);migrated=true}else w=P.empty()}
 saved=P.clone(w);render();if(!initial){dirty=true;generation++;await save()}if(migrated)notice('Your v0.5 library has been copied into v1.0.2. Story Books are now Projects. The original browser data was not changed. Download a full backup before continuing.');else if(recovered)notice('The last-good saved copy was recovered. Download a backup now; the original files remain on disk.');
 }catch(e){$('#app').innerHTML=`<main class="library"><h1>Your library is protected.</h1><p>${esc(e.message)}</p><p>No existing data was overwritten. Check the launcher window or keep your existing files and restore from a backup.</p><button data-action="import">Choose backup</button></main>`;bind($('#app'));lastError=e.message;status()}}
// Boot is owned by the v1.0.2 profile layer.
