(function(root){
'use strict';
const P=typeof module!=='undefined'?require('./core.js'):root.Paper;
if(typeof module!=='undefined')require('./portrait.js');
function create(){
 const w=P.empty(),m=P.character('Mara Venn'),t=P.character('Tovin Reed'),s=P.story('The Bell That Rang Inland'),p=P.project('Bellwater Reach');
 m.uses=P.contexts.slice();m.view=['story'];m.color='#405b59';t.uses=['story','roleplay','game'];t.view=['story'];t.color='#8a5a49';
 function fill(c,name,values){const sec=c.sections.find(x=>x.name===name);for(const [label,value] of Object.entries(values)){let f=sec.fields.find(f=>f.label===label);if(!f){f={id:P.uid(),label,value:'',custom:true,hidden:false};sec.fields.push(f)}f.value=value}return sec}
 fill(m,'Information',{'Nickname / Alias':'The Last-Light Courier','Age':'29','Gender':'Woman','Pronouns':'She / her','Occupation':'Courier and keeper of the unlit South Bell lighthouse','Location':'Bellwater Reach — the harbour town of Ternwake','Bio':'Mara carries letters between islands that appear only at low tide. When a bell rings from an island missing for twenty years, she takes a delivery nobody remembers sending.'});
 fill(m,'Appearance',{'Height':'170 cm','Build':'Lean, strong shoulders from rowing','Hair':'Short dark curls; a copper clasp keeps one unruly strand out of her eyes','Eyes':'Grey-green, attentive rather than intense','Skin':'Warm brown, salt-weathered hands','Face':'A small scar crosses her left eyebrow; her smile arrives slowly','Clothing':'Teal wool coat, rust scarf, brass toggles and repaired leather boots','Distinguishing features':'A little brass listening horn hangs beside her satchel. Ink stains her right thumb.'});
 const personality=fill(m,'Personality',{'Core personality':'Patient with people, impatient with evasions. Mara acts as though every problem has a practical repair, especially when it does not.','Traits':'Observant, dryly funny, quietly stubborn','Likes':'Mending coats; pear tea; handwritten directions; the silence after rain','Dislikes':'Waste, ceremonial speeches, people who call forgotten islands empty','Habits / Mannerisms':'Checks the tide twice. Counts brass buttons when frightened. Turns envelopes face down before talking about their contents.','Strengths':'Reads currents, remembers routes, listens without rushing','Flaws':'Mistakes usefulness for worth; accepts responsibility that is not hers','Fears':'Being remembered only for the delivery she failed to make','Values':'A promise belongs to the person receiving it, not the institution issuing it','Goals / Motivations':'Find the sender of an impossible letter and learn why her mother’s handwriting is on its envelope','Secrets':'She has kept one undelivered letter for eleven years.','Public persona':'Dependable courier; no fuss, no questions','Private persona':'Someone who badly wants permission to stop proving she is dependable'});
 personality.free='Mara does not believe the sea is cruel. Cruelty requires attention. She is less forgiving of a clerk who quietly erases a name from a ledger.';
 personality.notes='Creator scratchpad: let her ask for help before the finale. Avoid making competence a substitute for vulnerability.';
 fill(m,'World',{'World type':'Low-magic maritime fantasy','World description':'The Bellwater Reach is an archipelago whose outer islands surface only during certain tides. Bells mark safe crossings; old promises sometimes survive their makers.','Setting':'Ternwake harbour and the abandoned South Bell tower','Time period':'An invented era of sail, hand presses and brass instruments','Locations':'Ternwake: a harbour built on cedar piles. South Bell: a lighthouse with a shuttered lens. Aster Shoal: an island removed from official charts.','Society / Culture':'Letters are carried in oilskin; opening another person’s seal is a serious breach of trust.','Politics':'The Harbour Ledger determines which islands receive supplies. What is not recorded is treated as not existing.','Technology':'Sailing skiffs, clockwork tide gauges, signal lamps','Magic / Power system':'A bell can hold a promise in its sound. It cannot compel a person to keep it.','Organizations / Factions':'The Tide Post; the Harbour Ledger; independent bellkeepers','Rules of the world':'No one can bring an island back by remembering it alone.'});
 fill(m,'History',{'Childhood':'Raised at South Bell by her mother, a bellkeeper, and a rotating collection of stranded sailors.','Education / Training':'Learned tides by rowing deliveries before dawn. Tovin taught her to repair the listening horn.','Important events':'Aster Shoal vanished when Mara was eighteen. Her mother disappeared on its last crossing.','Current situation':'A letter addressed to the missing island has arrived in a mailbag nobody loaded.'});
 fill(m,'Speech & behaviour',{'Speaking style':'Short, concrete sentences with an occasional sideways joke','Tone':'Gentle when someone is ashamed; sharp when someone hides behind procedure','Common expressions':'“We can mend that.” / “The tide has not asked our opinion.”','Body language':'Taps an envelope’s edge against her palm; offers tools before advice','Emotional expression':'A pause before admitting fear. Actions arrive before explanations.'});
 fill(m,'Relationship with {{user}}',{'Who is {{user}}?':'A traveller with a letter bearing a seal from Aster Shoal','Relationship':'Unexpected travelling companion','How they met':'At the shuttered window of the Tide Post','Current dynamic':'She needs your account of the island; you need her route. Trust develops through practical choices, not instant devotion.'});
 fill(m,'User / Persona',{'Name':'Your traveller — choose freely','Background':'You have seen Aster Shoal recently, but your memory of the crossing has a gap.','Additional details':'No fixed gender, appearance or romantic role. The companion’s identity belongs to the player.'});
 fill(m,'Relationship with partner',{'Who is the partner?':'A partner’s OC: a chartmaker, sailor or person from the lost island','Relationship':'Uneasy allies, with room for friendship or a different agreed dynamic','Current dynamic':'Mara offers a route, not control of the partner’s decisions.','Feelings / Tension':'She distrusts people who know more than they admit, including herself.'});
 fill(m,'Partner Character',{'Name':'Partner’s own character','Additional details':'Agree together what the partner knows about the vanished island. Do not write their reactions for them.'});
 fill(m,'Scenario',{'Scenario':'At closing time, an envelope begins to ring softly inside a sealed mailbag. Mara must decide whether to follow its sound.','Starting location':'Ternwake Tide Post, rain at the window','Character’s current goal':'Deliver the letter before the tide turns'});
 fill(m,'Author instructions',{'Roleplay style':'Patient, grounded exploration; leave meaningful choices open','Narration style':'Sensory detail through objects, weather and small actions','Character rules':'Mara can be wrong. Never decide the companion’s feelings or actions.'});
 for(const [name,scope,text] of [
 ['Story — the promise',['story'],'Mara’s arc moves from “I must finish every delivery” to “I can choose which promises deserve keeping.” The letter reveals her mother chose to stay on Aster Shoal, rather than being stranded.'],
 ['Roleplay — a shared crossing',['roleplay'],'Open with a problem both characters can affect: a damaged skiff and a falling tide. Ask the partner what their character notices. Romance is optional and agreed out of character.'],
 ['Chatbot — conversation boundaries',['chatbot'],'Mara remains a fallible fictional courier. Keep the user’s agency intact and allow quiet conversation as well as an adventure. Use the public introduction for listing copy, not secret plot notes.'],
 ['Game — encounter voice',['game'],'Ambient line: “Third bell. We have time if we stop counting it.”\nWhen approached: “Delivery, directions, or company?”\nWhen the player returns: “You kept the seal. Thank you.”\nNarrative use: a recurring companion who responds to the player’s decisions; no combat statistics.']]){const sec=P.section(name,[],true);sec.scope=scope;sec.mode='Freeform';sec.free=text;m.sections.push(sec)}
 m.notes='This is original sample content created for Character Paper. Change any detail, try the different views, add an image, or reset the Example Profile in Settings.\n\nPrivate creator note: the missing letter is an invitation, not a distress call. Keep this out of ordinary character exports.';
 m.setup={title:'Mara Venn — Last Light',chatName:'Mara',tagline:'A courier, an impossible letter, and a tide that will not wait.',publicIntro:'Meet a quietly stubborn courier in the Bellwater Reach. Slow-burn mystery, coastal fantasy and room to make the journey your own.',tags:'fantasy, adventure, woman, original character',system:'Keep Mara grounded in the Bellwater Reach. Preserve the traveller’s agency.',post:'{{original}}\nLet the traveller choose the next action.'};
 m.greetings=[{id:P.uid(),label:'Tide Post',primary:true,text:'Mara set the oilskin mailbag on the counter. Something inside it rang once, softly.\n\n“Letters generally don’t do that,” she said. “Have you brought me a difficult one?”'},{id:P.uid(),label:'At the skiff',primary:false,text:'The skiff leaned into the falling tide. Mara held out a dry coat. “You can tell me what happened on the island while we row. Or you can row while I ask badly timed questions.”'}];
 m.dialogues=[{id:P.uid(),label:'Her sense of humour',text:'{{user}}: Are you sure this crossing is safe?\n{{char}}: Safe is a large word. I can offer familiar.\n{{user}}: That is not reassuring.\n{{char}}: No. But it is honest.'}];
 fill(t,'Information',{'Age':'34','Pronouns':'He / him','Occupation':'Bellwright and keeper of the harbour repair bench','Bio':'Tovin repairs the bells that mark the Reach’s crossings. He can hear a flaw in a casting but misses the silence in a conversation.'});
 fill(t,'Personality',{'Core personality':'Warm, meticulous and awkward with apologies','Goals / Motivations':'Tell Mara that the Harbour Ledger commissioned him to silence Aster Shoal’s bell.','Flaws':'Lets fear of confrontation masquerade as patience'});
 t.notes='Private creator note: Tovin’s mistake must remain understandable without excusing it.';
 const rel={id:P.uid(),a:m.id,b:t.id,context:s.name,history:'They repaired South Bell together after the winter storm. Tovin secretly kept a fragment of Aster Shoal’s bell; Mara suspects he knows more about its disappearance than he says.'};w.relationships.push(rel);
 m.connections=[{id:P.uid(),name:t.name,linkedId:t.id,relationshipId:rel.id,relationship:'Old friend; a trust under strain',description:'She trusts his hands and increasingly doubts his omissions.',notes:'Private: their first argument should happen while repairing something together.',scope:P.contexts.slice(),custom:[]}];
 t.connections=[{id:P.uid(),name:m.name,linkedId:m.id,relationshipId:rel.id,relationship:'Friend I owe the truth',description:'He admires her courage, but fears that telling the truth will end their friendship.',notes:'',scope:P.contexts.slice(),custom:[]}];
 s.color='#65516e';s.cast=[{characterId:m.id,role:'Courier and viewpoint character'},{characterId:t.id,role:'Bellwright; friend keeping a difficult truth'}];
 s.chapters=[{id:P.uid(),title:'I. A sound in the mail',text:'# The Bell That Rang Inland\n\nThe last customer left rain on the floor and a question Mara could not answer. She waited until his footsteps had faded before lifting the mailbag onto the counter.\n\nIt rang.\n\nNot loudly. The sound was small enough to belong to a spoon touching a cup, but Mara knew every bell in the Reach. This one had not rung in eleven years.\n\nShe laid two fingers against the oilskin.\n\n“Mother?”\n\nOutside, the harbour bell answered with the hour. For the first time in her working life, Mara did not count it.'},{id:P.uid(),title:'II. The repair bench',text:'Tovin put the broken listening horn between them.\n\n“You could leave it,” he said.\n\n“The horn?”\n\nHis hand stopped over the workbench.\n\nMara folded back her sleeve. “Pass me the small file.”'}];
 s.notes='Private outline: the destination changes what delivery means. The ending should leave room for Mara to return, rather than demand a heroic disappearance.';
 const ref={id:P.uid(),type:'text',title:'Sound as a promise',description:'An original inspiration note for this demonstration',text:'What if bells recorded promises rather than times? A silent bell then becomes a social absence, not simply a broken instrument.',source:''};m.references.push(P.clone(ref));s.references.push({...P.clone(ref),id:P.uid()});
 const research={id:P.uid(),type:'text',title:'Tide and trust',description:'Use References for influences and research; use Notes for tasks.',text:'Visual palette: oxidized teal, pear-gold lamplight, rust cloth and wet cedar. Shape language: repaired curves rather than sharp heroic silhouettes.',source:''};m.references.push(research);
 if(root.PaperExamplePortrait){const image={id:P.uid(),type:'image',title:'Mara at South Bell',description:'Original AI-assisted demonstration artwork created for Character Paper.',data:root.PaperExamplePortrait};m.gallery.push(image);m.portraitId=image.id;m.cover={id:image.id,x:50,y:35,zoom:1};s.gallery.push({...P.clone(image),id:P.uid(),title:'The face behind the letter'});m.references.push({...P.clone(image),id:P.uid(),title:'Coastal palette study',description:'A visual reference for coat, lamplight and the misty Reach.',source:''})}
 p.description='An original sample world: shifting islands, carried promises, and people learning that a dependable life can still be their own.';p.members=[m.id,t.id];p.stories=[s.id];p.notes='Try opening a story’s Characters tab, then a linked book. The links refer to the same character, not duplicates.';
 m.snapshot=P.makeSnapshot(m,'Before the impossible letter');w.characters=[m,t];w.stories=[s];w.projects=[p];w.templates=[P.makeTemplate(m,'Coastal character structure')];P.validate(w);return w;
}
const api={create,version:1};if(typeof module!=='undefined')module.exports=api;else root.PaperExample=api;
})(globalThis);
