(function(root){
'use strict';
const P=typeof module!=='undefined'?require('./core.js'):root.Paper;
const E=typeof module!=='undefined'?require('./example.js'):root.PaperExample;
const S=typeof module!=='undefined'?require('scrypt-js'):root.scrypt;
const enc=new TextEncoder(),dec=new TextDecoder();
const b64=a=>{const chunks=[];for(let i=0;i<a.length;i+=16384)chunks.push(String.fromCharCode(...a.subarray(i,i+16384)));return btoa(chunks.join(''))},bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0)),random=n=>crypto.getRandomValues(new Uint8Array(n)),hex=a=>[...a].map(n=>n.toString(16).padStart(2,'0')).join('');
async function seal(value,key){const iv=random(12),k=await crypto.subtle.importKey('raw',key,'AES-GCM',false,['encrypt']);const a=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(JSON.stringify(value))));return{iv:b64(iv),data:b64(a.slice(0,-16)),tag:b64(a.slice(-16))}}
async function open(box,key){const k=await crypto.subtle.importKey('raw',key,'AES-GCM',false,['decrypt']),data=bytes(box.data),tag=bytes(box.tag),all=new Uint8Array(data.length+tag.length);all.set(data);all.set(tag,data.length);return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(box.iv)},k,all)))}
async function derive(secret,salt,algorithm,iterations){if(typeof secret!=='string'||secret.length>512)throw Error('Invalid password.');if(algorithm==='pbkdf2-sha256'){if(!Number.isInteger(iterations)||iterations<100000||iterations>2000000)throw Error('Invalid password envelope.');const k=await crypto.subtle.importKey('raw',enc.encode(secret),'PBKDF2',false,['deriveBits']);return new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:bytes(salt),iterations},k,256))}if(algorithm)throw Error('Unsupported password envelope.');return S.scrypt(enc.encode(secret),bytes(salt),32768,8,1,32)}
async function wrap(key,secret){const salt=b64(random(16)),algorithm='pbkdf2-sha256',iterations=600000;return{salt,algorithm,iterations,box:await seal(b64(key),await derive(secret,salt,algorithm,iterations))}}
async function keyFor(r,secret='',recovery=false){if(r.passwordProtected===false){if(recovery)throw Error('This profile has no recovery key.');const k=bytes(r.localKey);if(k.length!==32)throw Error('Damaged profile key.');return k}try{const w=recovery?r.recovery:r.password;if(bytes(w.salt).length!==16||w.box.data.length>200)throw Error('Invalid envelope');return bytes(await open(w.box,await derive(secret,w.salt,w.algorithm,w.iterations)))}catch{throw Error('The password or recovery key is incorrect, or this file is damaged.')}}
function credentials(name,password,avatar='',enabled=true){if(typeof name!=='string'||!name.trim()||name.length>80)throw Error('Enter a profile name of 1–80 characters.');if(enabled&&(typeof password!=='string'||password.length<6||password.length>512))throw Error('Use a password of at least 6 characters.');if(typeof avatar!=='string'||avatar.length>3*1024*1024||avatar&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(avatar))throw Error('Choose a PNG, JPEG or WebP under 2 MB.')}
async function protection(key,password,enabled){if(!enabled)return{passwordProtected:false,localKey:b64(key),password:null,recovery:null,recoveryKey:null};const recoveryKey=hex(random(24)).match(/.{8}/g).join('-');return{passwordProtected:true,localKey:null,password:await wrap(key,password),recovery:await wrap(key,recoveryKey),recoveryKey}}
async function make(name,password,avatar,state,enabled=true){credentials(name,password,avatar,enabled);state=P.migrate(state);if(JSON.stringify(state).length>150*1024*1024)throw Error('Library exceeds 150 MB.');const key=random(32),p=await protection(key,password,enabled),recoveryKey=p.recoveryKey;delete p.recoveryKey;return{key,recoveryKey,record:{format:'character-paper-vault',version:1,id:P.uid(),name:name.trim(),avatar,...p,current:await seal(state,key),previous:null,revision:0,savedAt:Date.now(),backupAt:null}}}
const clean=r=>({id:r.id,name:r.name,avatar:r.avatar,passwordProtected:r.passwordProtected!==false,example:r.example===true,savedAt:r.savedAt,backupAt:r.backupAt});
function createBackend(storage){const sessions=new Map(),attempts=new Map();let queue=Promise.resolve();
 const read=async id=>{if(!/^[A-Za-z0-9-]{1,100}$/.test(id))throw Error('Invalid profile.');const r=await storage.read(id);if(!r)throw Error('Profile is missing. Restore a backup.');return r};
 async function list(){const result=[];for(const id of await storage.list()){try{result.push(clean(await read(id)))}catch{result.push({id,name:'Damaged profile — restore a backup',avatar:''})}}return result}
 async function install(){if((await list()).some(p=>p.example))return;const a=await make('Example Profile','','',E.create(),false);a.record.example=true;await storage.write(a.record);a.key.fill(0)}
 async function perform(route,b={},token=''){
 if(route==='bootstrap'){if(!await storage.marker()){await install();await storage.mark()}return{csrf:'local',profiles:await list(),hasLegacy:false}}
 if(route==='example-restore'){await install();return{ok:true}}
 if(route==='create'||route==='restore-profile'){let state=P.empty();if(route==='restore-profile'){if(b.backup?.format==='character-paper-vault'){const k=await keyFor(b.backup,b.secret,!!b.useRecovery);state=P.migrate(await open(b.backup.current,k));k.fill(0)}else state=P.migrate(b.backup)}const a=await make(b.name,b.password,b.avatar||'',state,b.passwordProtected!==false);await storage.write(a.record);a.key.fill(0);return{profile:clean(a.record),recoveryKey:a.recoveryKey}}
 if(route==='unlock'||route==='recover'){const now=Date.now();if(now-(attempts.get(b.id)||0)<1500)throw Error('Please wait a moment before trying again.');attempts.set(b.id,now);const r=await read(b.id),key=await keyFor(r,b.secret,route==='recover');let state,recovered=false;try{state=P.migrate(await open(r.current,key))}catch{if(!r.previous)throw Error('Saved data is damaged. Restore a backup.');state=P.migrate(await open(r.previous,key));recovered=true}if(route==='recover'){credentials(r.name,b.password,r.avatar);r.password=await wrap(key,b.password);await storage.write(r);for(const [t,s] of sessions)if(s.id===r.id){s.key.fill(0);sessions.delete(t)}}const t=hex(random(32));sessions.set(t,{id:r.id,key});return{token:t,state,revision:r.revision,profile:clean(r),recovered}}
 const s=sessions.get(token);if(!s)throw Error('Profile is locked. Unlock it to continue.');let r=await read(s.id);
 if(route==='lock'){s.key.fill(0);sessions.delete(token);return{ok:true}}
 if(route==='delete-profile'){if(b.confirmName!==r.name)throw Error('Enter the profile name to confirm deletion.');if(r.passwordProtected!==false){const k=await keyFor(r,b.secret);k.fill(0)}await storage.remove(r.id);for(const [t,x] of sessions)if(x.id===r.id){x.key.fill(0);sessions.delete(t)}return{ok:true}}
 if(route==='example-reset'){if(!r.example)throw Error('This is not the Example Profile.');const state=E.create();r.current=await seal(state,s.key);r.previous=null;r.revision++;r.savedAt=Date.now();await storage.write(r);return{state,revision:r.revision,profile:clean(r)}}
 if(route==='decode-backup'){const k=await keyFor(b.backup,b.secret,!!b.useRecovery);try{return{state:P.migrate(await open(b.backup.current,k))}}finally{k.fill(0)}}
 if(route==='library'){P.validate(b.state);if(JSON.stringify(b.state).length>150*1024*1024)throw Error('Library exceeds 150 MB.');if(b.revision!==r.revision)throw Error('Another window saved this profile. Back up and reopen it.');try{await open(r.current,s.key);r.previous=r.current}catch{}r.current=await seal(b.state,s.key);r.revision++;r.savedAt=Date.now();await storage.write(r);return{revision:r.revision,savedAt:r.savedAt}}
 if(route==='backup'){P.validate(b.state);const backup={...r,current:await seal(b.state,s.key),previous:null,backupAt:Date.now()};r.backupAt=backup.backupAt;await storage.write(r);return{backup}}
 if(route==='protection'){if(typeof b.enabled!=='boolean')throw Error('Choose password protection.');if(r.passwordProtected!==false){const k=await keyFor(r,b.currentPassword);k.fill(0)}credentials(r.name,b.password,r.avatar,b.enabled);const current=await open(r.current,s.key),previous=r.previous?await open(r.previous,s.key):null,key=random(32),p=await protection(key,b.password,b.enabled),recoveryKey=p.recoveryKey;delete p.recoveryKey;r={...r,...p,current:await seal(current,key),previous:previous?await seal(previous,key):null};await storage.write(r);for(const [t,x] of sessions)if(x.id===s.id){x.key.fill(0);if(t!==token)sessions.delete(t)}s.key=key;return{profile:clean(r),recoveryKey}}
 if(route==='profile'){credentials(b.name,'placeholder',b.avatar||'');r.name=b.name.trim();r.avatar=b.avatar||'';await storage.write(r);return{profile:clean(r)}}
 if(route==='location'||route==='open-folder')return{path:storage.location||'This app’s private local storage. Export a backup to choose a folder you can access.'};
 throw Error('Unknown operation.');
 }
 return{call(route,b,token){const op=queue.then(()=>perform(route,b,token));queue=op.catch(()=>{});return op}};
}
const api={createBackend,seal,open,keyFor,make,wrap};if(typeof module!=='undefined')module.exports=api;else root.PaperLocal=api;
})(globalThis);
