'use strict';
const beforeReleaseAction=action,beforeReleaseBind=bind,beforeReleaseSettings=settings09,beforeReleaseProfile=profileForm09,beforeReleaseAbout=aboutPage09,beforeReleaseProfiles=profilesPage09,beforeReleaseOptions=bookOptions;
const supportHtml=()=>`<h2>Contact ANVA</h2><p><a href="https://anva-studio.github.io/" target="_blank" rel="noopener noreferrer">Website</a> · <a href="https://forms.gle/W7qtQRmqxgZkLtS9" target="_blank" rel="noopener noreferrer">Feedback & bug reports</a> · <a href="mailto:Anvahq@gmail.com">Anvahq@gmail.com</a></p><p>For a bug, include your app version, operating system, what you were doing, what you expected, what happened, and steps to reproduce it if you know them.</p><p class="quiet">Do not send passwords or recovery keys. Share private or sensitive character content only if it is genuinely necessary to resolve the issue.</p><p class="quiet">Character Paper ${PaperRelease.version} · Build ${PaperRelease.build} · ${esc(PaperRelease.platform)}</p>`;
const releaseQuestions=[
 ['What is Character Paper?','A local home for fictional characters, stories, and the details around them. Start with a name and write only the sections you need. Nothing has to be completed.'],
 ['How do I start?','Open your workspace and create a profile, or open the password-free Example Profile. Inside your profile, create a character, story or project. Click your profile name or picture to edit it.'],
 ['What are Story, Roleplay, Chatbot and Game contexts?','Used for controls library filtering. View as chooses which sections and connections you see. All shows every context; Custom lets you combine them. Applies to controls a section or connection’s scope. Switching views hides information without deleting it. Game is another writing context, not a game engine.'],
 ['How do Structured and Freeform work?','Structured gives you labelled fields. Freeform gives you a blank writing space. Both versions remain stored when you switch. Exports let you choose one or both.'],
 ['Can I add my own fields?','Use Custom field or Custom section. Section options lets you rename, reorder, remove or set its contexts. Existing information stays saved when a different view hides it.'],
 ['What are Notes and scratchpads for?','Rough thoughts, reminders, spoilers and unfinished ideas belong in Loose pages, private section notes or connection notes. They stay in full backups, but ordinary character and manuscript exports leave them out. Public introduction / Creator’s Notes in Chatbot Setup is public listing copy and does export.'],
 ['How do I use the Example Profile?','It contains Mara Venn, a courier in the original Bellwater Reach setting, a linked friend and a short story. It has no password and is fully editable. Try the contexts, gallery, references, connections and private notes.'],
 ['How do I reset or restore the example?','Open Settings inside the Example Profile and choose Reset Example Profile. This replaces its edits with the app’s latest sample. If you deleted it, use Restore Example Profile in Help or the profile picker. It will not return automatically on launch.'],
 ['How do I delete or archive data?','Book options offers Archive, which hides a book from the ordinary library and can be undone from the archive view. To delete a profile, click its name or picture and choose Delete profile; type the name and confirm. Back it up first if you may need it again. Deleting a profile removes its books from this device.'],
 ['Can I import a character card?','Restore accepts full Character Paper JSON backups, including older supported libraries. It is not an arbitrary CHub or Janitor card importer. Character card JSON is an export format; use a full profile backup to move your whole workspace.'],
 ['My changes are not saving. What should I do?','Keep the app open. Check the save indicator, retry, and create a backup of your unsaved writing if needed. Check free device space. Never delete a damaged save until you have kept a copy.'],
 ['How does Android save and export work?','Profiles stay in the app’s private storage. Backup and export open Android’s Save file picker, where you choose a destination you can access. Restore and Add images use the normal file picker. Updating the same app preserves its data; uninstalling may remove local profiles, so keep backups.'],
 ['How do I get help?','Search this FAQ, explore the Example Profile, then contact ANVA if you are still stuck. The feedback form is suitable for bugs and suggestions; email is available for general help.']
];
aboutPage09=function(creator=false){let html=beforeReleaseAbout(creator);if(creator)return html.replace(/<h2>Find ANVA<\/h2>[\s\S]*?(?=<h2>Leave a little encouragement)/,supportHtml());html=html.replace('<h2 id="faq">','<label class="help-search">Search Help<input id="help-search" type="search" placeholder="Try backups, contexts or notes"></label><p id="help-results" class="quiet" aria-live="polite"></p><h2 id="faq">').replace('<h2>Tips for your next writing session</h2>',releaseQuestions.map(([q,a])=>`<details class="release-faq"><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')+`${btn('Restore Example Profile','example-restore','','flat')}<h2>Tips for your next writing session</h2>`);return html.replace('</main>',supportHtml()+'</main>')};
profilesPage09=function(){return beforeReleaseProfiles().replace('Your stories stay on this device.','Your stories stay on this device. The Example Profile is editable sample content.').replace('</main>',btn('Restore Example Profile','example-restore','','flat')+'</main>')};
settings09=function(){beforeReleaseSettings();const heading=modal.querySelector('h3');heading?.insertAdjacentHTML('beforebegin',`<div class="story-actions">${profile09.example?btn('Reset Example Profile','example-reset'):btn('Restore Example Profile','example-restore')}</div>`);if(typeof PaperNative!=='undefined')modal.querySelector('[data-action="folder09"]')?.remove();bind(modal)};
profileForm09=function(restore=false,edit=false){beforeReleaseProfile(restore,edit);if(edit){modal.querySelector('.dialog-actions').insertAdjacentHTML('afterbegin',btn('Delete profile','profile-delete','','danger'));modal.querySelector('[data-action="profile-delete"]').onclick=()=>action('profile-delete')}};
bookOptions=function(){beforeReleaseOptions();if(object()?.kind==='character')modal.querySelector('.option-grid').insertAdjacentHTML('beforeend',btn('Delete book','delete-book','','danger'));bind(modal)};
bind=function(root){beforeReleaseBind(root);const search=root.querySelector('#help-search');if(search)search.oninput=()=>{const q=search.value.trim().toLowerCase();let visible=0;document.querySelectorAll('.about-page details').forEach(d=>{d.hidden=!d.textContent.toLowerCase().includes(q);if(!d.hidden)visible++});$('#help-results').textContent=q?`${visible} answers found`:''};if(modal.open&&modal.querySelector('[data-action="remove-section"]')&&!modal.querySelector('[data-action="section-scope"]')){modal.querySelector('.story-actions').insertAdjacentHTML('beforeend',btn('Applies to contexts','section-scope'));beforeReleaseBind(modal)}};
function clearDeletedProfile(){clearTimeout(timer);token='';profile09=null;w=P.empty();saved=null;dirty=false;saving=null;undo=[];redo=[];lastError='';ui.id=null;screen09='profiles';closeDialog()}
action=async function(name,value){
 if(name==='example-restore'){await api09('example-restore');await refreshProfiles09();if(!profile09)screen09='profiles';render();notice('The Example Profile is available in your profile picker. If it already existed, your edits were kept.');return}
 if(name==='example-reset')return confirmAction('Reset Example Profile?','This replaces all edits in the Example Profile with the latest original sample, including books, notes, images and snapshots. Back up first if you want to keep your version.',async()=>{try{clearTimeout(timer);if(saving)await saving;const r=await api09('example-reset');w=P.migrate(r.state);saved=P.clone(w);revision=r.revision;profile09=r.profile;dirty=false;undo=[];redo=[];lastError='';ui.id=null;ui.page='home';render()}catch(e){notice(e.message)}});
 if(name==='profile-delete'){dialog('Delete this profile?',`<p>This deletes <strong>${esc(profile09.name)}</strong> and all its saved books on this device. Create a backup first if you want to keep them.</p><label>Type the profile name<input id="delete-profile-name" autocomplete="off"></label>${profile09.passwordProtected!==false?'<label>Current password<input id="delete-profile-secret" type="password" autocomplete="current-password"></label>':''}`, [['Cancel','close-modal'],['Delete profile','profile-delete-confirm','','danger']]);return}
 if(name==='profile-delete-confirm'){if($('#delete-profile-name').value!==profile09.name)return inlineError09(Error('Enter the exact profile name.'));const secret=$('#delete-profile-secret')?.value;return submit09(async()=>{clearTimeout(timer);if(saving)await saving;await api09('delete-profile',{confirmName:profile09.name,secret});clearDeletedProfile();await refreshProfiles09();render()})}
 if(name==='section-scope'){const s=object().sections.find(s=>s.id===ui.tab);dialog('Applies to contexts',`<p>Hiding a section never deletes its writing.</p>${P.contexts.map(c=>`<label class="check"><input name="section-context" type="checkbox" value="${c}" ${s.scope.includes(c)?'checked':''}>${c[0].toUpperCase()+c.slice(1)}</label>`).join('')}`,[['Apply','section-scope-apply','','primary']]);return}
 if(name==='section-scope-apply'){const selected=[...modal.querySelectorAll('[name="section-context"]:checked')].map(x=>x.value);if(!selected.length)return inlineError09(Error('Choose at least one context.'));transact(()=>{object().sections.find(s=>s.id===ui.tab).scope=selected;ui.tab='Loose pages'});closeDialog();return}
 if(name==='delete-book'){const o=object();return confirmAction('Delete this character book?','Its details will be removed. Linked stories and projects will keep their other books. You can undo this during this session.',()=>transact(()=>{w.characters=w.characters.filter(x=>x.id!==o.id);w.relationships=w.relationships.filter(r=>r.a!==o.id&&r.b!==o.id);for(const c of w.characters)c.connections=c.connections.filter(x=>x.linkedId!==o.id);for(const p of w.projects)p.members=p.members.filter(id=>id!==o.id);for(const s of w.stories)s.cast=s.cast.filter(x=>x.characterId!==o.id);ui.id=null;ui.page='characters'}))}
 return beforeReleaseAction(name,value);
};
