'use strict';
const crypto=require('node:crypto'),fs=require('node:fs/promises'),path=require('node:path'),{promisify}=require('node:util');
const P=require('./core.js'),scrypt=promisify(crypto.scrypt),pbkdf2=promisify(crypto.pbkdf2);
const derive=(password,salt)=>scrypt(password,Buffer.from(salt,'base64'),32,{N:32768,r:8,p:1,maxmem:64*1024*1024});
function seal(value,key){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key,iv),data=Buffer.concat([c.update(JSON.stringify(value),'utf8'),c.final()]);return{iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),data:data.toString('base64')}}
function open(box,key){const d=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(box.iv,'base64'));d.setAuthTag(Buffer.from(box.tag,'base64'));return JSON.parse(Buffer.concat([d.update(Buffer.from(box.data,'base64')),d.final()]).toString('utf8'))}
async function wrap(key,password){const salt=crypto.randomBytes(16).toString('base64');return{salt,box:seal(key.toString('base64'),await derive(password,salt))}}
async function unwrap(wrapped,password){try{if(typeof password!=='string'||password.length>512||typeof wrapped?.salt!=='string'||Buffer.from(wrapped.salt,'base64').length!==16||wrapped.box.data.length>200)throw Error('Invalid key envelope');let derived;if(wrapped.algorithm==='pbkdf2-sha256'){if(!Number.isInteger(wrapped.iterations)||wrapped.iterations<100000||wrapped.iterations>2000000)throw Error('Invalid KDF work factor');derived=await pbkdf2(password,Buffer.from(wrapped.salt,'base64'),wrapped.iterations,32,'sha256')}else{if(wrapped.algorithm)throw Error('Unsupported KDF');derived=await derive(password,wrapped.salt)}const key=Buffer.from(open(wrapped.box,derived),'base64');derived.fill(0);if(key.length!==32)throw Error('Invalid key');return key}catch{throw Error('The password or recovery key is incorrect, or this file is damaged.')}}
function credentials(name,password,avatar=''){if(typeof name!=='string'||!name.trim()||name.length>80)throw Error('Enter a profile name of 1–80 characters.');if(typeof password!=='string'||password.length<6||password.length>512)throw Error('Use a password of at least 6 characters.');if(typeof avatar!=='string'||avatar.length>3*1024*1024||avatar&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(avatar))throw Error('Choose a PNG, JPEG or WebP profile picture under 2 MB.')}
const protectedProfile=r=>r.passwordProtected!==false;
async function keyFor(r,secret='',recovery=false){if(protectedProfile(r))return unwrap(recovery?r.recovery:r.password,secret);if(recovery)throw Error('This profile does not use a password or recovery key.');if(typeof r.localKey!=='string'||!/^[A-Za-z0-9+/]{43}=$/.test(r.localKey))throw Error('Profile key is damaged. Restore a backup.');return Buffer.from(r.localKey,'base64')}
async function protection(key,password,enabled){if(!enabled)return{fields:{passwordProtected:false,localKey:key.toString('base64'),password:null,recovery:null},recoveryKey:null};const recoveryKey=crypto.randomBytes(24).toString('hex').match(/.{8}/g).join('-');return{fields:{passwordProtected:true,localKey:null,password:await wrap(key,password),recovery:await wrap(key,recoveryKey)},recoveryKey}}
async function make(name,password,avatar,state,enabled=true){credentials(name,enabled?password:'no-password',avatar);state=P.migrate(state);if(JSON.stringify(state).length>150*1024*1024)throw Error('Library exceeds 150 MB.');const key=crypto.randomBytes(32),p=await protection(key,password,enabled);return{key,recoveryKey:p.recoveryKey,record:{format:'character-paper-vault',version:1,id:crypto.randomUUID(),name:name.trim(),avatar,...p.fields,current:seal(state,key),previous:null,revision:0,savedAt:Date.now(),backupAt:null}}}
async function changeProtection(r,oldKey,password,enabled){credentials(r.name,enabled?password:'no-password',r.avatar);const current=open(r.current,oldKey),previous=r.previous?open(r.previous,oldKey):null,key=crypto.randomBytes(32),p=await protection(key,password,enabled);return{key,recoveryKey:p.recoveryKey,record:{...r,...p.fields,current:seal(current,key),previous:previous?seal(previous,key):null}}}
function vault(dir){
 const location=id=>{if(!/^[a-zA-Z0-9-]{1,100}$/.test(id))throw Error('Invalid profile.');return path.join(dir,id+'.json')};
 async function read(id){return JSON.parse(await fs.readFile(location(id),'utf8'))}
 async function write(record){await fs.mkdir(dir,{recursive:true});const file=location(record.id),tmp=file+'.pending',h=await fs.open(tmp,'w');try{await h.writeFile(JSON.stringify(record));await h.sync()}finally{await h.close()}await fs.rename(tmp,file)}
 async function list(){await fs.mkdir(dir,{recursive:true});const result=[];for(const name of await fs.readdir(dir)){if(!name.endsWith('.json'))continue;try{const r=await read(name.slice(0,-5));result.push({id:r.id,name:r.name,avatar:r.avatar,passwordProtected:protectedProfile(r),example:r.example===true})}catch{result.push({id:name.slice(0,-5),name:'Damaged profile — restore a backup',avatar:''})}}return result}
 return{read,write,list};
}
module.exports={seal,open,wrap,unwrap,make,vault,credentials,keyFor,protectedProfile,changeProtection};
